import re

with open("src/data.ts", "r") as f:
    text = f.read()

replacements = {
    # Tarantino
    '''description: "L'odyssée sanglante, cocasse et dramatique de deux tueurs à gages bavards, d'un boxeur sur le déclin, de la séduisante femme d'un caïd de la pègre et de deux braqueurs amateurs d'un restaurant de quartier."''': '''description: "The bloody, comical and dramatic odyssey of two talkative hitmen, a fading boxer, the seductive wife of a mob boss and two amateur robbers in a local diner."''',
    '''tagline: "La vie n'est pas un long fleuve tranquille au pays des malfrats."''': '''tagline: "Life is not a long quiet river in the land of thugs."''',
    '''description: "Au cours de son mariage, une ex-tueuse à gages subit l'attaque sanglante de son ancien amant et employeur, Bill. Sortie d'un coma de quatre ans, la Mariée n'a plus qu'un but de survie : se venger méthodiquement."''': '''description: "During her wedding, a former hitwoman is violently attacked by her former lover and boss, Bill. Waking up from a four-year coma, the Bride has only one goal for survival: exact methodical revenge."''',
    '''description: "Après s'être débarrassée de ses premières cibles, la Mariée poursuit sa vengeance implacable contre Budd et Elle Driver. Son face-à-face final et inévitable avec son mentor et bourreau, Bill, approche."''': '''description: "After eliminating her first targets, the Bride continues her relentless revenge against Budd and Elle Driver. Her final and inevitable confrontation with her mentor and tormentor, Bill, is approaching."''',
    '''description: "Dans la France occupée, une jeune Juive propriétaire d'un cinéma prépare une vengeance incendiaire, tandis qu'un commando de soldats juifs américains, les 'Basterds', sèment la terreur chez l'occupant en scalpant leurs adversaires."''': '''description: "In occupied France, a young Jewish cinema owner plots an incendiary revenge, while a commando of Jewish-American soldiers, the 'Basterds', spread terror among the occupiers by scalping their enemies."''',
    '''description: "Deux ans avant la Guerre de Sécession, Django, un esclave, s'associe au docteur King Schultz, un excentrique chasseur de primes allemand. Schultz libère Django et l'aide à retrouver sa femme Broomhilda, retenue dans la plantation du cruel Calvin Candie."''': '''description: "Two years before the Civil War, Django, a slave, teams up with Dr. King Schultz, an eccentric German bounty hunter. Schultz frees Django and helps him find his wife Broomhilda, held in the plantation of the cruel Calvin Candie."''',
    '''description: "En 1969 de l'âge d'or hollywoodien, Rick Dalton, star déclinante de séries télévisées de westerns, et Cliff Booth, sa doublure cascade impassible de toujours, errent dans un milieu qu'ils ne reconnaissent plus."''': '''description: "In 1969 of the Hollywood Golden Age, Rick Dalton, a fading star of western TV series, and Cliff Booth, his impassive longtime stunt double, wander in a world they no longer recognize."''',
    '''tagline: "Un conte de fées mélancolique et flamboyant sur le cinéma."''': '''tagline: "A melancholic and flamboyant fairy tale about cinema."''',
    '''description: "Quelques années après la Guerre de Sécession, un chasseur de primes renommé et sa prisonnière se retrouvent bloqués par un terrible blizzard de montagne dans un refuge de diligence aux côtés de six clients suspects de complot."''': '''description: "A few years after the Civil War, a renowned bounty hunter and his prisoner are stranded by a terrible mountain blizzard in a stagecoach refuge alongside six suspects of a conspiracy."''',

    # Nolan
    '''description: "Dom Cobb est un voleur expérimenté dans l'art de soustraire des secrets enfouis dans le subconscient des gens pendant qu'ils rêvent. Pour retrouver sa vie et ses enfants, il doit accomplir l'impossible : implanter une idée dans l'esprit d'un homme."''': '''description: "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state. To get his life back, he must do the impossible: inception."''',
    '''tagline: "Votre esprit est la scène du crime."''': '''tagline: "Your mind is the scene of the crime."''',
    '''description: "Alors que la Terre s'éteint doucement, un groupe d'astronautes et d'ingénieurs intrépides franchit une faille spatio-temporelle récemment découverte pour tenter de trouver une planète capable de sauver l'humanité."''': '''description: "As Earth slowly dies, a group of intrepid astronauts and engineers travel through a newly discovered wormhole in an attempt to find a habitable planet to save humanity."''',
    '''tagline: "L'amour est la seule chose qui transcende le temps et l'espace."''': '''tagline: "Love is the one thing that transcends time and space."''', # Missed this one previously? Wait, I will add it anyway.
    '''description: "Marqué par l'assassinat de ses parents, Bruce Wayne voyage à travers le monde pour trouver une arme pour combattre l'injustice. De retour à Gotham infesté par le crime, il dévoile son alter-ego masqué."''': '''description: "Marked by the murder of his parents, Bruce Wayne travels the world to find a weapon to fight injustice. Returning to crime-infested Gotham, he unveils his masked alter-ego."''',
    '''tagline: "Ce n'est pas qui je suis en dessous, mais ce que je fais qui me définit."''': '''tagline: "It's not who I am underneath, but what I do that defines me."''',
    '''description: "Batman hausse sa lutte contre la pègre de Gotham avec l'aide du lieutenant Jim Gordon et du procureur Harvey Dent. Mais un génie du crime anarchiste et sadique connu sous le nom du Joker plonge la ville dans un chaos indescriptible."''': '''description: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent. But a sadistically anarchic criminal mastermind known as the Joker plunges the city into chaos."''',
    '''description: "Huit ans après la mort d'Harvey Dent, Batman a disparu de Gotham. Cependant, l'apparition d'une voleuse de bijoux astucieuse et d'un terroriste impitoyable nommé Bane forcent Bruce Wayne à sortir d'un long exil physique."''': '''description: "Eight years after the death of Harvey Dent, Batman has vanished from Gotham. However, the appearance of a cunning cat burglar and a ruthless terrorist named Bane forces Bruce Wayne out of his long physical exile."''',
    '''tagline: "La légende s'achève dans le feu."''': '''tagline: "The legend ends in fire."''',
    '''description: "En mai 1940, environ 400 000 soldats des armées alliées se retrouvent encerclés et piégés sur la plage de Dunkerque par les armées allemandes. L'évacuation navale la plus audacieuse de l'histoire s'organise."''': '''description: "In May 1940, some 400,000 Allied soldiers found themselves surrounded and trapped on the beach of Dunkirk by the German army. The most daring naval evacuation in history is organized."''',
    '''description: "Armé d'un seul mot – Tenet – et luttant pour sa survie, le Protagoniste voyage à travers le crépuscule de l'espionnage international. Sa mission cruciale : empêcher une menace plus grave encore qu'une apocalypse nucléaire, en inversant la flèche du temps."''': '''description: "Armed with only one word—Tenet—and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time."''',
    '''description: "Le physicien J. Robert Oppenheimer prend la tête du projet top-secret Manhattan au désert du Nouveau-Mexique avec un groupe de scientifiques brillants pour développer la première bombe atomique, changeant à jamais l'histoire du monde."''': '''description: "Physicist J. Robert Oppenheimer takes the lead on the top-secret Manhattan Project in the New Mexico desert with a group of brilliant scientists to develop the first atomic bomb, forever changing the course of history."''',

    # Star Wars
    '''description: "Deux chevaliers Jedi protègent la reine Amidala de Naboo et découvrent par hasard sur la sablonneuse Tatooine un jeune esclave d'un talent exceptionnel nommé Anakin Skywalker, réceptacle d'une prophétie galactique."''': '''description: "Two Jedi Knights escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their original glory."''',
    '''tagline: "La destinée d'un prodige galactique s'éveille."''': '''tagline: "The destiny of a galactic prodigy awakens."''',
    '''description: "Dix ans après, Anakin Skywalker est le padawan d'Obi-Wan Kenobi. Alors qu'une mystérieuse menace de séparatisme grandit, Anakin tombe amoureux de la sénatrice Padmé Amidala tandis qu'une armée secrète de clones se prépare."''': '''description: "Ten years later, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the Senator and discovers a secret clone army crafted for the Jedi."''',
    '''tagline: "Une passion interdite dans une galaxie à l'aube du conflit."''': '''tagline: "A forbidden passion in a galaxy on the dawn of conflict."''',
    '''description: "Le jeune fermier Luke Skywalker sur Tatooine se retrouve entraîné dans un conflit intergalactique lorsqu'il intercepte un message de détresse de la princesse Leia, retenue par l'Empire et sa redoutable Étoile de la Mort."''': '''description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader."''',
    '''description: "L'Empire traque impitoyablement les rebelles dispersés. Pendant que Han Solo et Leia fuient vers la Cité des Nuages, Luke Skywalker entame son entraînement rigoureux de Jedi sur la planète marécageuse de Dagobah auprès du maître Yoda."''': '''description: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader."''',
    '''tagline: "Le Côté Obscur se dévoile. Une vérité fracassante."''': '''tagline: "The Dark Side reveals itself. A shattering truth."''',
    '''description: "Luke Skywalker organise une mission pour libérer Han Solo de Jabba le Hutt avant d'affronter son père, Dark Vador, et l'Empereur Palpatine en personne sur la lune forestière d'Endor pour le destin de l'univers."''': '''description: "After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap."''',
    '''tagline: "L'affrontement final pour la rédemption d'un père."''': '''tagline: "The final showdown for a father's redemption."''',
    '''description: "Rey tente de convaincre le légendaire Luke Skywalker, aigri et exilé sur son île isolée, de la guider dans l'usage de la Force, tandis que la Résistance tente d'échapper à une poursuite spatiale implacable du Premier Ordre mené par Kylo Ren."''': '''description: "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order."''',
    '''tagline: "Brisez le passé pour réécrire l'avenir galactique."''': '''tagline: "Break the past to rewrite the galactic future."''',
    '''description: "Alors que l'Empereur Palpatine réapparaît mystérieusement d'entre les morts dans l'ombre galactique, Rey et la Résistance lancent un assaut ultime désespéré contre les forces sith de la \\"Flotte éternelle\\"."''': '''description: "The surviving members of the resistance face the First Order once again, and the legendary conflict between the Jedi and the Sith reaches its peak bringing the Skywalker saga to its end."''',

    # James Bond
    '''description: "L'agent d'élite britannique James Bond est envoyé en Jamaïque pour enquêter sur la disparition mystérieuse d'un chef de station locale. Il découvre le repaire secret du maléfique Dr No sur l'île de Crab Key."''': '''description: "A resourceful British government agent seeks answers in a case involving the disappearance of a colleague and the disruption of the American space program."''',
    '''tagline: "Présentation mondiale de l'agent 007."''': '''tagline: "The worldwide introduction of Agent 007."''',
    '''description: "Bond enquête sur les tractations financières d'Auric Goldfinger, un richissime homme d'affaires obsédé par l'or, et met au jour son plan démoniaque d'assaut de la réserve d'or fédérale de Fort Knox."''': '''description: "While investigating a gold magnate's smuggling, James Bond uncovers a plot to contaminate the Fort Knox gold reserve."''',
    '''description: "Pour sa toute première mission en tant qu'agent double-Zéro, James Bond doit affronter Le Chiffre, banquier d'un réseau terroriste mondial, dans une partie de poker clandestine à hauts enjeux au Casino Royale au Monténégro."''': '''description: "After earning 00 status and a licence to kill, Secret Agent James Bond sets out on his first mission as 007. Bond must defeat a private banker funding terrorists in a high-stakes game of poker at Casino Royale, Montenegro."''',
    '''tagline: "Découvrez comment Bond est devenu 007."''': '''tagline: "Discover how Bond became 007."''',
    '''description: "La fidélité de Bond envers sa supérieure M est ébranlée alors que les secrets du passé tumultueux de celle-ci menacent de détruire le MI6, cyber-attaqué par un ancien agent vengeur d'une incroyable noirceur, Silva."''': '''description: "James Bond's loyalty to M is tested when her past comes back to haunt her. When MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost."''',
    '''tagline: "Le passé resurgit toujours au cœur d'un hiver écossais."''': '''tagline: "The past always resurfaces in the heart of a Scottish winter."''',
    '''description: "Bond a quitté le MI6 pour couler des jours tranquilles en Jamaïque. Mais un vieil ami de la CIA réapparaît pour lui demander de sauver un scientifique kidnappé détenant une technologie nanorobotique dévastatrice."''': '''description: "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology."''',
    '''tagline: "L'adieu triomphal du commandant Bond."''': '''tagline: "The triumphant farewell of Commander Bond."''',
    
    # Leftovers
    '''tagline: "Je suis devenu la Mort, le destructeur des mondes."''': '''tagline: "Now I am become Death, the destroyer of worlds."''',
    '''tagline: "La fin glorieuse de la grande saga Skywalker."''': '''tagline: "The glorious end of the great Skywalker saga."''',
    '''tagline: "L'amour est la seule chose qui transcende le temps et l'espace."''': '''tagline: "Love is the one thing that transcends time and space."''',
    '''tagline: "Il y a bien longtemps, dans une galaxie lointaine..."''': '''tagline: "A long time ago, in a galaxy far, far away..."''',
    '''tagline: "Tout ce qu'il touche se change en or."''': '''tagline: "Everything he touches turns to gold."''',
}

for fr, en in replacements.items():
    text = text.replace(fr, en)
    # also attempt fixing double quotes escaping
    text = text.replace(fr.replace('\\"', '"'), en)

with open("src/data.ts", "w") as f:
    f.write(text)

