export interface Movie {
  id: string;
  title: string;
  year: number;
  duration: string;
  rating: string;
  director: string;
  cast: string[];
  castDetails?: { id: string; name: string; role?: string; imageUrl?: string; }[];
  genre: string[];
  description: string;
  gradient: string; // Tailwind gradient colors e.g., 'from-slate-900 to-indigo-950'
  accentColor: string; // Tailwind text/border e.g., 'text-indigo-400 font-bold border-indigo-400'
  accentHex: string; // Hex code for custom badges and glows
  symbol: string; // Emoji symbols reflecting theme for graphic poster layout
  tagline: string;
  streamUrl?: string;
  posterUrl?: string;
  backdropUrl?: string;
  isJellyfin?: boolean;
  originalTitle?: string;
  studios?: string[];
  providerIds?: Record<string, string>;
}

export interface Collection {
  id: string;
  title: string;
  description: string;
  movies: Movie[];
}

export const COLLECTIONS: Collection[] = [
  {
    id: "john-wick",
    title: "John Wick",
    description: "The art of war and choreographed revenge. A legendary action saga led by Keanu Reeves.",
    movies: [
      {
        id: "john-wick-1",
        title: "John Wick",
        year: 2014,
        duration: "101 min",
        rating: "7.4",
        director: "Chad Stahelski",
        cast: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Willem Dafoe"],
        genre: ["Action", "Thriller"],
        description: "Un ancien tueur à gages légendaire sort de sa retraite pour traquer les truands qui ont assassiné son chiot, dernier cadeau inestimable de sa défunte épouse, et volé sa Mustang chérie.",
        gradient: "from-slate-900 via-neutral-900 to-amber-950/40",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🐕✖️🔫",
        tagline: "N'auriez-û pas dû toucher à son chien."
      },
      {
        id: "john-wick-2",
        title: "John Wick: Chapter 2",
        year: 2017,
        duration: "122 min",
        rating: "7.5",
        director: "Chad Stahelski",
        cast: ["Keanu Reeves", "Common", "Laurence Fishburne", "Riccardo Scamarcio"],
        genre: ["Action", "Crime", "Thriller"],
        description: "John Wick est contraint de sortir à nouveau de sa retraite par un ancien associé qui souhaite s'emparer d'une cabale de tueurs internationaux. Lié par un serment de sang inviolable, John se rend à Rome.",
        gradient: "from-slate-900 via-neutral-900 to-cyan-950/40",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🪙🩸🏛️",
        tagline: "Le serment de sang est inviolable."
      },
      {
        id: "john-wick-3",
        title: "John Wick: Chapter 3 - Parabellum",
        year: 2019,
        duration: "131 min",
        rating: "7.4",
        director: "Chad Stahelski",
        cast: ["Keanu Reeves", "Halle Berry", "Ian McShane", "Laurence Fishburne"],
        genre: ["Action", "Thriller"],
        description: "Excommunié de la Grande Table et privé de tous ses droits, John Wick a sa tête mise à prix pour 14 millions de dollars. Une armée de tueurs est lancée à ses trousses à travers les rues de New York.",
        gradient: "from-slate-900 via-neutral-900 to-purple-950/40",
        accentColor: "text-purple-400 border-purple-400/30 bg-purple-400/10",
        accentHex: "#c084fc",
        symbol: "🌧️🐎🤵",
        tagline: "Si tu veux la paix, prépare la guerre."
      },
      {
        id: "john-wick-4",
        title: "John Wick: Chapter 4",
        year: 2023,
        duration: "169 min",
        rating: "7.7",
        director: "Chad Stahelski",
        cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård", "Laurence Fishburne"],
        genre: ["Action", "Crime", "Thriller"],
        description: "John Wick découvre le moyen de vaincre l'organisation criminelle de la Grande Table. Mais pour gagner sa liberté, il doit affronter un nouvel ennemi féroce doté d'alliances mondiales et transformer de vieux amis en redoutables adversaires.",
        gradient: "from-slate-900 via-neutral-900 to-rose-950/40",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "⏳🏯⚔️",
        tagline: "Pas de quartier sur les marches du Sacré-Cœur."
      }
    ]
  },
  {
    id: "indiana-jones",
    title: "Indiana Jones",
    description: "The whip, the hat and the mysteries of history. Follow the greatest archaeologist-adventurer of all time.",
    movies: [
      {
        id: "indy-1",
        title: "Raiders of the Lost Ark",
        year: 1981,
        duration: "115 min",
        rating: "8.4",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Karen Allen", "Paul Freeman", "John Rhys-Davies"],
        genre: ["Adventure", "Action"],
        description: "Indy est chargé d'une mission périlleuse par les services secrets américains : retrouver l'Arche d'Alliance, coffre contenant les Tables de la Loi, convoitée par les nazis car censée conférer des pouvoirs d'invincibilité militaire.",
        gradient: "from-neutral-900 via-amber-950/30 to-amber-950/40",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🤠📜🏺",
        tagline: "La quête de l'impossible commence ici."
      },
      {
        id: "indy-2",
        title: "Indiana Jones and the Temple of Doom",
        year: 1984,
        duration: "118 min",
        rating: "7.5",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Kate Capshaw", "Ke Huy Quan", "Amrish Puri"],
        genre: ["Adventure", "Action"],
        description: "En Inde, Indiana Jones, un jeune garçon astucieux appelé Demi-Lune et une chanteuse de cabaret se retrouvent dans un village appauvri. Leurs habitants les supplient de retrouver une pierre sacrée mystique volée par un culte sanguinaire adepte de sacrifices humains.",
        gradient: "from-neutral-900 via-red-950/30 to-amber-950/40",
        accentColor: "text-red-400 border-red-400/30 bg-red-400/10",
        accentHex: "#f87171",
        symbol: "🏮🛒💎",
        tagline: "Une aventure d'une noirceur mystique absolue."
      },
      {
        id: "indy-3",
        title: "Indiana Jones and the Last Crusade",
        year: 1989,
        duration: "127 min",
        rating: "8.2",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Sean Connery", "Alison Doody", "Denholm Elliott"],
        genre: ["Adventure", "Action"],
        description: "Indiana Jones part sur les traces de son père, le professeur Henry Jones, mystérieusement disparu alors qu'il recherchait le légendaire Saint Graal. Ensemble, le père et le fils s'unissent pour surmonter des épreuves millénaires.",
        gradient: "from-neutral-900 via-amber-950/30 to-yellow-950/40",
        accentColor: "text-yellow-500 border-yellow-500/30 bg-yellow-500/10",
        accentHex: "#eab308",
        symbol: "🏆🛡️⚔️",
        tagline: "Le Graal n'attend que les cœurs purs."
      },
      {
        id: "indy-4",
        title: "Indiana Jones et le Royaume du Crâne de Cristal",
        year: 2008,
        duration: "122 min",
        rating: "6.2",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Cate Blanchett", "Shia LaBeouf", "Karen Allen"],
        genre: ["Adventure", "Science Fiction"],
        description: "En 1957, en pleine Guerre Froide, Indiana Jones est mêlé à un complot soviétique visant à décoder les secrets d'un mystérieux crâne de cristal découvert en Amazonie, lié à des civilisations disparues et d'autres dimensions.",
        gradient: "from-neutral-900 via-emerald-950/30 to-teal-950/40",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "👽💀🌴",
        tagline: "Le secret de l'Amazonie dépasse notre monde."
      },
      {
        id: "indy-5",
        title: "Indiana Jones et le Cadran de la Destinée",
        year: 2023,
        duration: "154 min",
        rating: "6.6",
        director: "James Mangold",
        cast: ["Harrison Ford", "Phoebe Waller-Bridge", "Mads Mikkelsen", "Antonio Banderas"],
        genre: ["Adventure", "Action"],
        description: "En 1969, sur fond de conquête spatiale, le célèbre archéologue se prépare à prendre sa retraite. Mais l'apparition de sa filleule Helena et d'un ancien nazi travaillant pour la NASA le replonge dans une course contre la montre temporelle.",
        gradient: "from-neutral-900 via-yellow-950/20 to-stone-900",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "⚙️🕰️✈️",
        tagline: "Contre le temps, le voyage ultime commence."
      }
    ]
  },
  {
    id: "tarantino-collection",
    title: "Quentin Tarantino",
    description: "Punchy dialogue, stylized violence and unforgettable soundtracks. The unique work of master Quentin Tarantino.",
    movies: [
      {
        id: "pulp-fiction",
        title: "Pulp Fiction",
        year: 1994,
        duration: "154 min",
        rating: "8.9",
        director: "Quentin Tarantino",
        cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
        genre: ["Crime", "Drama"],
        description: "L'odyssée sanglante, cocasse et dramatique de deux tueurs à gages bavards, d'un boxeur sur le déclin, de la séduisante femme d'un caïd de la pègre et de deux braqueurs amateurs d'un restaurant de quartier.",
        gradient: "from-red-950 via-neutral-900 to-amber-950/40",
        accentColor: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
        accentHex: "#facc15",
        symbol: "💃🍔💼",
        tagline: "La vie n'est pas un long fleuve tranquille au pays des malfrats."
      },
      {
        id: "reservoir-dogs",
        title: "Reservoir Dogs",
        year: 1992,
        duration: "99 min",
        rating: "8.3",
        director: "Quentin Tarantino",
        cast: ["Harvey Keitel", "Tim Roth", "Michael Madsen", "Steve Buscemi"],
        genre: ["Crime", "Thriller"],
        description: "Six criminels professionnels, qui ne se connaissent pas, sont engagés par un parrain pour cambrioler un diamantaire. Le hold-up tourne au carnage sanglant et les rescapés se regroupent dans un entrepôt abandonné, suspectant un traître.",
        gradient: "from-stone-900 via-neutral-900 to-red-950/50",
        accentColor: "text-neutral-200 border-neutral-400/30 bg-neutral-400/10",
        accentHex: "#e5e5e5",
        symbol: "🕶️🤵💎",
        tagline: "Pas de vrais noms, pas de quartier."
      },
      {
        id: "kill-bill-1",
        title: "Kill Bill: Vol. 1",
        year: 2003,
        duration: "111 min",
        rating: "8.2",
        director: "Quentin Tarantino",
        cast: ["Uma Thurman", "Lucy Liu", "Vivica A. Fox", "David Carradine"],
        genre: ["Action", "Crime"],
        description: "Au cours de son mariage, une ex-tueuse à gages subit l'attaque sanglante de son ancien amant et employeur, Bill. Sortie d'un coma de quatre ans, la Mariée n'a plus qu'un but de survie : se venger méthodiquement.",
        gradient: "from-yellow-950 via-neutral-900 to-amber-950/30",
        accentColor: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
        accentHex: "#eab308",
        symbol: "🥻⚔️🩸",
        tagline: "La vengeance est un plat qui se mange froid."
      },
      {
        id: "kill-bill-2",
        title: "Kill Bill: Vol. 2",
        year: 2004,
        duration: "137 min",
        rating: "8.0",
        director: "Quentin Tarantino",
        cast: ["Uma Thurman", "David Carradine", "Michael Madsen", "Daryl Hannah"],
        genre: ["Action", "Crime"],
        description: "Après s'être débarrassée de ses premières cibles, la Mariée poursuit sa vengeance implacable contre Budd et Elle Driver. Son face-à-face final et inévitable avec son mentor et bourreau, Bill, approche.",
        gradient: "from-amber-950 via-neutral-900 to-stone-950",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "🐍🥋🎯",
        tagline: "Le dernier chapitre de sa liste noire."
      },
      {
        id: "inglourious-basterds",
        title: "Inglourious Basterds",
        year: 2009,
        duration: "153 min",
        rating: "8.3",
        director: "Quentin Tarantino",
        cast: ["Brad Pitt", "Mélanie Laurent", "Christoph Waltz", "Michael Fassbender"],
        genre: ["War", "Drama", "Action"],
        description: "Dans la France occupée, une jeune Juive propriétaire d'un cinéma prépare une vengeance incendiaire, tandis qu'un commando de soldats juifs américains, les 'Basterds', sèment la terreur chez l'occupant en scalpant leurs adversaires.",
        gradient: "from-red-950 via-stone-900 to-neutral-950",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🎦🎖️🪓",
        tagline: "Une réécriture explosive de la grande Histoire."
      },
      {
        id: "django-unchained",
        title: "Django Unchained",
        year: 2012,
        duration: "165 min",
        rating: "8.5",
        director: "Quentin Tarantino",
        cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington"],
        genre: ["Western", "Drama"],
        description: "Deux ans avant la Guerre de Sécession, Django, un esclave, s'associe au docteur King Schultz, un excentrique chasseur de primes allemand. Schultz libère Django et l'aide à retrouver sa femme Broomhilda, retenue dans la plantation du cruel Calvin Candie.",
        gradient: "from-amber-950 via-neutral-900 to-red-950/40",
        accentColor: "text-amber-400 border-amber-400/30 bg-amber-400/10",
        accentHex: "#fbbf24",
        symbol: "🐎🩸⛓️",
        tagline: "La liberté n'est pas négociable, elle s'arrache."
      },
      {
        id: "once-upon-a-time",
        title: "Once Upon a Time in Hollywood",
        year: 2019,
        duration: "161 min",
        rating: "7.6",
        director: "Quentin Tarantino",
        cast: ["Leonardo DiCaprio", "Brad Pitt", "Margot Robbie", "Emile Hirsch"],
        genre: ["Drama", "Comedy"],
        description: "En 1969 de l'âge d'or hollywoodien, Rick Dalton, star déclinante de séries télévisées de westerns, et Cliff Booth, sa doublure cascade impassible de toujours, errent dans un milieu qu'ils ne reconnaissent plus.",
        gradient: "from-yellow-950/40 via-neutral-900 to-amber-950/40",
        accentColor: "text-amber-300 border-amber-300/30 bg-amber-300/10",
        accentHex: "#fde047",
        symbol: "🎬🎙️🐕",
        tagline: "Un conte de fées mélancolique et flamboyant sur le cinéma."
      },
      {
        id: "the-hateful-eight",
        title: "The Hateful Eight",
        year: 2015,
        duration: "168 min",
        rating: "7.8",
        director: "Quentin Tarantino",
        cast: ["Samuel L. Jackson", "Kurt Russell", "Jennifer Jason Leigh", "Walton Goggins"],
        genre: ["Western", "Crime", "Mystère"],
        description: "Quelques années après la Guerre de Sécession, un chasseur de primes renommé et sa prisonnière se retrouvent bloqués par un terrible blizzard de montagne dans un refuge de diligence aux côtés de six clients suspects de complot.",
        gradient: "from-stone-900 via-zinc-900 to-blue-950/30",
        accentColor: "text-sky-300 border-sky-300/30 bg-sky-300/10",
        accentHex: "#7dd3fc",
        symbol: "❄️🛖🥃",
        tagline: "Huit menteurs. Aucun ne sortira indemne."
      }
    ]
  },
  {
    id: "christopher-nolan",
    title: "Christopher Nolan",
    description: "Distorted time, fragmented reality and visions of unparalleled scale. The conceptual cinema of Christopher Nolan.",
    movies: [
      {
        id: "inception",
        title: "Inception",
        year: 2010,
        duration: "148 min",
        rating: "8.8",
        director: "Christopher Nolan",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
        genre: ["Science Fiction", "Action", "Thriller"],
        description: "Dom Cobb est un voleur expérimenté dans l'art de soustraire des secrets enfouis dans le subconscient des gens pendant qu'ils rêvent. Pour retrouver sa vie et ses enfants, il doit accomplir l'impossible : implanter une idée dans l'esprit d'un homme.",
        gradient: "from-indigo-950 via-slate-900 to-slate-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🌀🌀🎲",
        tagline: "Votre esprit est la scène du crime."
      },
      {
        id: "interstellar",
        title: "Interstellar",
        year: 2014,
        duration: "169 min",
        rating: "8.7",
        director: "Christopher Nolan",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        genre: ["Science Fiction", "Drama", "Adventure"],
        description: "Alors que la Terre s'éteint doucement, un groupe d'astronautes et d'ingénieurs intrépides franchit une faille spatio-temporelle récemment découverte pour tenter de trouver une planète capable de sauver l'humanité.",
        gradient: "from-blue-950 via-indigo-950/50 to-neutral-950",
        backdropUrl: "https://www.wallpaperflare.com/static/536/846/466/interstellar-movie-movies-interstellar-movie-wallpaper.jpg",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "🪐🚀🌾",
        tagline: "L'amour est la seule chose qui transcende le temps et l'espace."
      },
      {
        id: "batman-begins",
        title: "Batman Begins",
        year: 2005,
        duration: "140 min",
        rating: "8.2",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Michael Caine", "Liam Neeson", "Katie Holmes"],
        genre: ["Action", "Drama"],
        description: "Marqué par l'assassinat de ses parents, Bruce Wayne voyage à travers le monde pour trouver une arme pour combattre l'injustice. De retour à Gotham infesté par le crime, il dévoile son alter-ego masqué.",
        gradient: "from-slate-900 via-neutral-900 to-stone-900/40",
        accentColor: "text-neutral-400 border-neutral-400/30 bg-neutral-400/10",
        accentHex: "#a3a3a3",
        symbol: "🦇⛩️🏙️",
        tagline: "Ce n'est pas qui je suis en dessous, mais ce que je fais qui me définit."
      },
      {
        id: "the-dark-knight",
        title: "The Dark Knight",
        year: 2008,
        duration: "152 min",
        rating: "9.0",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
        genre: ["Action", "Crime", "Drama"],
        description: "Batman hausse sa lutte contre la pègre de Gotham avec l'aide du lieutenant Jim Gordon et du procureur Harvey Dent. Mais un génie du crime anarchiste et sadique connu sous le nom du Joker plonge la ville dans un chaos indescriptible.",
        gradient: "from-blue-950/30 via-neutral-900 to-stone-950",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🃏🔥🌃",
        tagline: "Pourquoi cet air si sérieux ?"
      },
      {
        id: "the-dark-knight-rises",
        title: "The Dark Knight Rises",
        year: 2012,
        duration: "164 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"],
        genre: ["Action", "Thriller"],
        description: "Huit ans après la mort d'Harvey Dent, Batman a disparu de Gotham. Cependant, l'apparition d'une voleuse de bijoux astucieuse et d'un terroriste impitoyable nommé Bane forcent Bruce Wayne à sortir d'un long exil physique.",
        gradient: "from-zinc-900 via-slate-900 to-stone-900/50",
        accentColor: "text-slate-400 border-slate-400/30 bg-slate-400/10",
        accentHex: "#94a3b8",
        symbol: "🕸️💥🎙️",
        tagline: "La légende s'achève dans le feu."
      },
      {
        id: "dunkirk",
        title: "Dunkirk",
        year: 2017,
        duration: "106 min",
        rating: "7.8",
        director: "Christopher Nolan",
        cast: ["Fionn Whitehead", "Tom Hardy", "Mark Rylance", "Cillian Murphy"],
        genre: ["War", "Drama", "History"],
        description: "En mai 1940, environ 400 000 soldats des armées alliées se retrouvent encerclés et piégés sur la plage de Dunkerque par les armées allemandes. L'évacuation navale la plus audacieuse de l'histoire s'organise.",
        gradient: "from-sky-950/30 via-slate-900 to-zinc-900",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "🏖️⚓✈️",
        tagline: "Le temps est le pire des ennemis."
      },
      {
        id: "tenet",
        title: "Tenet",
        year: 2020,
        duration: "150 min",
        rating: "7.3",
        director: "Christopher Nolan",
        cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki", "Kenneth Branagh"],
        genre: ["Science Fiction", "Action", "Espionage"],
        description: "Armé d'un seul mot – Tenet – et luttant pour sa survie, le Protagoniste voyage à travers le crépuscule de l'espionnage international. Sa mission cruciale : empêcher une menace plus grave encore qu'une apocalypse nucléaire, en inversant la flèche du temps.",
        gradient: "from-indigo-950 via-neutral-900 to-teal-950/20",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "◀️▶️🚢",
        tagline: "N'essayez pas de comprendre, ressentez-le."
      },
      {
        id: "oppenheimer",
        title: "Oppenheimer",
        year: 2023,
        duration: "180 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
        genre: ["Biography", "Drama", "History"],
        description: "Le physicien J. Robert Oppenheimer prend la tête du projet top-secret Manhattan au désert du Nouveau-Mexique avec un groupe de scientifiques brillants pour développer la première bombe atomique, changeant à jamais l'histoire du monde.",
        gradient: "from-amber-950/50 via-neutral-900 to-stone-950",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "☢️🔬🤯",
        tagline: "Je suis devenu la Mort, le destructeur des mondes."
      }
    ]
  },
  {
    id: "star-wars",
    title: "Star Wars",
    description: "The legendary space saga. An eternal struggle between the Force and the Dark Side across the galaxy.",
    movies: [
      {
        id: "sw-1",
        title: "Episode I: The Phantom Menace",
        year: 1999,
        duration: "136 min",
        rating: "6.5",
        director: "George Lucas",
        cast: ["Liam Neeson", "Ewan McGregor", "Natalie Portman", "Jake Lloyd"],
        genre: ["Science Fiction", "Adventure"],
        description: "Deux chevaliers Jedi protègent la reine Amidala de Naboo et découvrent par hasard sur la sablonneuse Tatooine un jeune esclave d'un talent exceptionnel nommé Anakin Skywalker, réceptacle d'une prophétie galactique.",
        gradient: "from-blue-950/30 via-neutral-900 to-amber-950/30",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "🏜️⚔️👹",
        tagline: "La destinée d'un prodige galactique s'éveille."
      },
      {
        id: "sw-2",
        title: "Episode II: Attack of the Clones",
        year: 2002,
        duration: "142 min",
        rating: "6.6",
        director: "George Lucas",
        cast: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen", "Christopher Lee"],
        genre: ["Science Fiction", "Adventure"],
        description: "Dix ans après, Anakin Skywalker est le padawan d'Obi-Wan Kenobi. Alors qu'une mystérieuse menace de séparatisme grandit, Anakin tombe amoureux de la sénatrice Padmé Amidala tandis qu'une armée secrète de clones se prépare.",
        gradient: "from-indigo-950/40 via-neutral-900 to-slate-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🪐🧪🤖",
        tagline: "Une passion interdite dans une galaxie à l'aube du conflit."
      },
      {
        id: "sw-3",
        title: "Episode III: Revenge of the Sith",
        year: 2005,
        duration: "140 min",
        rating: "7.6",
        director: "George Lucas",
        cast: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen", "Ian McDiarmid"],
        genre: ["Science Fiction", "Adventure"],
        description: "Trois ans après le début de la Guerre des Clones, Anakin Skywalker est tiraillé entre sa loyauté envers les Jedi et les tentations d'un pouvoir obscur proposé par le Chancelier Palpatine dans le but de sauver sa femme.",
        gradient: "from-red-950/60 via-neutral-900 to-stone-900",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🌋⚔️💀",
        tagline: "La naissance tragique de Dark Vador."
      },
      {
        id: "sw-4",
        title: "Episode IV: A New Hope",
        year: 1977,
        duration: "121 min",
        rating: "8.6",
        director: "George Lucas",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
        genre: ["Science Fiction", "Adventure"],
        description: "Le jeune fermier Luke Skywalker sur Tatooine se retrouve entraîné dans un conflit intergalactique lorsqu'il intercepte un message de détresse de la princesse Leia, retenue par l'Empire et sa redoutable Étoile de la Mort.",
        gradient: "from-neutral-900 via-blue-950/30 to-slate-900",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🏜️🚀🔵",
        tagline: "Il y a bien longtemps, dans une galaxie lointaine..."
      },
      {
        id: "sw-5",
        title: "Episode V: The Empire Strikes Back",
        year: 1980,
        duration: "124 min",
        rating: "8.7",
        director: "Irvin Kershner",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"],
        genre: ["Science Fiction", "Adventure"],
        description: "L'Empire traque impitoyablement les rebelles dispersés. Pendant que Han Solo et Leia fuient vers la Cité des Nuages, Luke Skywalker entame son entraînement rigoureux de Jedi sur la planète marécageuse de Dagobah auprès du maître Yoda.",
        gradient: "from-sky-950/40 via-neutral-900 to-slate-950",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "❄️🐸🪐",
        tagline: "Le Côté Obscur se dévoile. Une vérité fracassante."
      },
      {
        id: "sw-6",
        title: "Episode VI: Return of the Jedi",
        year: 1983,
        duration: "131 min",
        rating: "8.3",
        director: "Richard Marquand",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"],
        genre: ["Science Fiction", "Adventure"],
        description: "Luke Skywalker organise une mission pour libérer Han Solo de Jabba le Hutt avant d'affronter son père, Dark Vador, et l'Empereur Palpatine en personne sur la lune forestière d'Endor pour le destin de l'univers.",
        gradient: "from-emerald-950/30 via-neutral-900 to-stone-900",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "🌳⚡⚔️",
        tagline: "L'affrontement final pour la rédemption d'un père."
      },
      {
        id: "sw-7",
        title: "Episode VII: The Force Awakens",
        year: 2015,
        duration: "138 min",
        rating: "7.8",
        director: "J.J. Abrams",
        cast: ["Daisy Ridley", "John Boyega", "Oscar Isaac", "Adam Driver"],
        genre: ["Science Fiction", "Adventure"],
        description: "Une nouvelle menace surgit des cendres de l'Empire : le Premier Ordre. Rey, une pilleuse d'épaves solitaire, s'associe à Finn, un stormtrooper déserteur, et Han Solo pour retrouver la trace du dernier maître Jedi, Luke Skywalker.",
        gradient: "from-neutral-900 via-zinc-900 to-purple-950/30",
        accentColor: "text-purple-400 border-purple-400/30 bg-purple-400/10",
        accentHex: "#c084fc",
        symbol: "🧭🌅🔵",
        tagline: "Une nouvelle génération de héros face au Côté Obscur."
      },
      {
        id: "sw-8",
        title: "Episode VIII: The Last Jedi",
        year: 2017,
        duration: "152 min",
        rating: "6.9",
        director: "Rian Johnson",
        cast: ["Daisy Ridley", "John Boyega", "Mark Hamill", "Carrie Fisher"],
        genre: ["Science Fiction", "Adventure"],
        description: "Rey tente de convaincre le légendaire Luke Skywalker, aigri et exilé sur son île isolée, de la guider dans l'usage de la Force, tandis que la Résistance tente d'échapper à une poursuite spatiale implacable du Premier Ordre mené par Kylo Ren.",
        gradient: "from-rose-950/30 via-neutral-900 to-stone-900",
        accentColor: "text-rose-400 border-rose-400/30 bg-rose-400/10",
        accentHex: "#f43f5e",
        symbol: "🪨🦅🔴",
        tagline: "Brisez le passé pour réécrire l'avenir galactique."
      },
      {
        id: "sw-9",
        title: "Episode IX: The Rise of Skywalker",
        year: 2019,
        duration: "142 min",
        rating: "6.4",
        director: "J.J. Abrams",
        cast: ["Daisy Ridley", "Adam Driver", "John Boyega", "Oscar Isaac"],
        genre: ["Science Fiction", "Adventure"],
        description: "Alors que l'Empereur Palpatine réapparaît mystérieusement d'entre les morts dans l'ombre galactique, Rey et la Résistance lancent un assaut ultime désespéré contre les forces sith de la " + '"Flotte éternelle".',
        gradient: "from-cyan-950/30 via-neutral-900 to-slate-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "⚡🔮🛸",
        tagline: "La fin glorieuse de la grande saga Skywalker."
      },
      {
        id: "sw-rogue-one",
        title: "Rogue One: A Star Wars Story",
        year: 2016,
        duration: "133 min",
        rating: "7.8",
        director: "Gareth Edwards",
        cast: ["Felicity Jones", "Diego Luna", "Ben Mendelsohn", "Donnie Yen"],
        genre: ["Science Fiction", "Action", "War"],
        description: "Un groupe de rebelles disparates s'unissent pour une mission suicide de renseignement militaire : voler les plans secrets de l'Étoile de la Mort, l'arme de destruction massive ultime de l'Empire.",
        gradient: "from-zinc-900 via-neutral-900 to-slate-950/40",
        accentColor: "text-teal-400 border-teal-400/30 bg-teal-400/10",
        accentHex: "#2dd4bf",
        symbol: "🏖️🚨🎖️",
        tagline: "Le vol audacieux qui déclencha l'espoir."
      }
    ]
  },
  {
    id: "james-bond",
    title: "James Bond",
    description: "British composure, high-tech gadgets and a license to kill. The greatest missions of the iconic spy.",
    movies: [
      {
        id: "bond-dr-no",
        title: "James Bond contre Dr No",
        year: 1962,
        duration: "110 min",
        rating: "7.2",
        director: "Terence Young",
        cast: ["Sean Connery", "Ursula Andress", "Joseph Wiseman", "Jack Lord"],
        genre: ["Action", "Adventure", "Espionage"],
        description: "L'agent d'élite britannique James Bond est envoyé en Jamaïque pour enquêter sur la disparition mystérieuse d'un chef de station locale. Il découvre le repaire secret du maléfique Dr No sur l'île de Crab Key.",
        gradient: "from-slate-900 via-neutral-900 to-blue-950/30",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🏝️🦀🤵",
        tagline: "Présentation mondiale de l'agent 007."
      },
      {
        id: "bond-goldfinger",
        title: "Goldfinger",
        year: 1964,
        duration: "110 min",
        rating: "7.7",
        director: "Terence Young",
        cast: ["Sean Connery", "Honor Blackman", "Gert Fröbe", "Harold Sakata"],
        genre: ["Action", "Espionage"],
        description: "Bond enquête sur les tractations financières d'Auric Goldfinger, un richissime homme d'affaires obsédé par l'or, et met au jour son plan démoniaque d'assaut de la réserve d'or fédérale de Fort Knox.",
        gradient: "from-stone-900 via-neutral-900 to-amber-950/40",
        accentColor: "text-amber-400 border-amber-400/30 bg-amber-400/10",
        accentHex: "#fbbf24",
        symbol: "👑🚗🪙",
        tagline: "Tout ce qu'il touche se change en or."
      },
      {
        id: "bond-casino-royale",
        title: "Casino Royale",
        year: 2006,
        duration: "144 min",
        rating: "8.0",
        director: "Martin Campbell",
        cast: ["Daniel Craig", "Eva Green", "Mads Mikkelsen", "Judi Dench"],
        genre: ["Espionage", "Action", "Thriller"],
        description: "Pour sa toute première mission en tant qu'agent double-Zéro, James Bond doit affronter Le Chiffre, banquier d'un réseau terroriste mondial, dans une partie de poker clandestine à hauts enjeux au Casino Royale au Monténégro.",
        gradient: "from-neutral-900 via-neutral-950 to-red-950/30",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "🃏🥃🤵",
        tagline: "Découvrez comment Bond est devenu 007."
      },
      {
        id: "bond-skyfall",
        title: "Skyfall",
        year: 2012,
        duration: "143 min",
        rating: "7.8",
        director: "Sam Mendes",
        cast: ["Daniel Craig", "Javier Bardem", "Judi Dench", "Ralph Fiennes"],
        genre: ["Espionage", "Action"],
        description: "La fidélité de Bond envers sa supérieure M est ébranlée alors que les secrets du passé tumultueux de celle-ci menacent de détruire le MI6, cyber-attaqué par un ancien agent vengeur d'une incroyable noirceur, Silva.",
        gradient: "from-slate-900 via-blue-950/20 to-neutral-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🏚️🚁🚇",
        tagline: "Le passé resurgit toujours au cœur d'un hiver écossais."
      },
      {
        id: "bond-no-time-to-die",
        title: "No Time to Die",
        year: 2021,
        duration: "163 min",
        rating: "7.3",
        director: "Cary Joji Fukunaga",
        cast: ["Daniel Craig", "Rami Malek", "Léa Seydoux", "Lashana Lynch"],
        genre: ["Espionage", "Action"],
        description: "Bond a quitté le MI6 pour couler des jours tranquilles en Jamaïque. Mais un vieil ami de la CIA réapparaît pour lui demander de sauver un scientifique kidnappé détenant une technologie nanorobotique dévastatrice.",
        gradient: "from-neutral-900 via-zinc-900 to-indigo-950/30",
        accentColor: "text-slate-200 border-slate-300/30 bg-slate-300/10",
        accentHex: "#e2e8f0",
        symbol: "🚤🧬🥀",
        tagline: "L'adieu triomphal du commandant Bond."
      }
    ]
  },
  {
    id: "rocky",
    title: "Rocky",
    description: "The fight of a lifetime. The inspiring rise of the Italian Stallion from a humble Philadelphia neighborhood to the top of the world.",
    movies: [
      {
        id: "rocky-1",
        title: "Rocky",
        year: 1976,
        duration: "120 min",
        rating: "8.1",
        director: "John G. Avildsen",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Carl Weathers"],
        genre: ["Sport", "Drama"],
        description: "Rocky Balboa, a boxer from a seedy Philadelphia club accumulating debts, is offered by a stroke of destiny to face the undefeated world champion Apollo Creed for a historic main event.",
        gradient: "from-neutral-900 via-amber-950/30 to-zinc-900",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🥊🏃🥩",
        tagline: "Everyone deserves a chance at glory."
      },
      {
        id: "rocky-2",
        title: "Rocky II",
        year: 1979,
        duration: "119 min",
        rating: "7.3",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Carl Weathers"],
        genre: ["Sport", "Drama"],
        description: "After heroically going the distance against world champion Apollo Creed, the public demands a spectacular rematch. Rocky Balboa first tries to settle down with his family before returning to the ring.",
        gradient: "from-neutral-900 via-stone-900 to-amber-950/20",
        accentColor: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
        accentHex: "#facc15",
        symbol: "💍🦁👊",
        tagline: "A rematch the whole world was waiting for."
      },
      {
        id: "rocky-3",
        title: "Rocky III",
        year: 1982,
        duration: "99 min",
        rating: "6.9",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Mr. T"],
        genre: ["Sport", "Drama"],
        description: "Rocky has rested on his laurels and suffers a crushing knockout defeat to the fierce and arrogant Clubber Lang. Apollo Creed, his former rival, steps up as an unexpected mentor to give him back the 'eye of the tiger'.",
        gradient: "from-neutral-900 via-amber-950/30 to-neutral-950",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "🐯🏆⚡",
        tagline: "Rediscover the will to win."
      },
      {
        id: "rocky-4",
        title: "Rocky IV",
        year: 1985,
        duration: "91 min",
        rating: "6.9",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Talia Shire", "Carl Weathers", "Dolph Lundgren"],
        genre: ["Sport", "Drama"],
        description: "When his lifelong friend Apollo Creed dies tragically in the ring killed by the ruthless Soviet colossus Ivan Drago, Rocky Balboa decides to train hard in the heart of the wild Siberia to face him in Moscow.",
        gradient: "from-blue-950/40 via-red-950/30 to-neutral-900",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🧥❄️🇷🇺",
        tagline: "A fight that transcends geopolitical borders."
      },
      {
        id: "rocky-5",
        title: "Rocky V",
        year: 1990,
        duration: "104 min",
        rating: "5.3",
        director: "John G. Avildsen",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Tommy Morrison"],
        genre: ["Sport", "Drama"],
        description: "Financially ruined and forced to retire from boxing due to physical aftereffects, Rocky returns to the Philadelphia suburbs and trains a fiery young prodigy named Tommy Gunn.",
        gradient: "from-neutral-900 via-zinc-950 to-stone-900",
        accentColor: "text-neutral-400 border-neutral-400/30 bg-neutral-400/10",
        accentHex: "#94a3b8",
        symbol: "🏚️👦🏼🧥",
        tagline: "The real fight isn't in the ring."
      },
      {
        id: "rocky-6",
        title: "Rocky Balboa",
        year: 2006,
        duration: "102 min",
        rating: "7.1",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Burt Young", "Antonio Tarver", "Geraldine Hughes"],
        genre: ["Sport", "Drama"],
        description: "Owning a modest restaurant, Rocky still suffers from Adrian's death. When a TV simulation declares him the virtual winner of the current champion, Rocky agrees to don the gloves again for a final rematch of honor.",
        gradient: "from-stone-950 via-neutral-900 to-amber-950/15",
        accentColor: "text-amber-400 border-amber-400/30 bg-amber-400/10",
        accentHex: "#fbbf24",
        symbol: "🍽️🐕🏟️",
        tagline: "It's about how hard you can get hit and keep moving forward."
      }
    ]
  },
  {
    id: "terminator",
    title: "Terminator",
    description: "Human resistance against the uprising of Skynet and cyborgs. A time loop of pure cybernetic action.",
    movies: [
      {
        id: "terminator-1",
        title: "Terminator",
        year: 1984,
        duration: "107 min",
        rating: "8.1",
        director: "James Cameron",
        cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn"],
        genre: ["Science Fiction", "Action"],
        description: "En 1984, un tueur cybernétique froid conçu par Skynet – le T-800 – est envoyé depuis l'an 2029 pour éliminer Sarah Connor, dont le futur fils John mènera victorieusement l'humanité face aux machines.",
        gradient: "from-blue-950/50 via-neutral-900 to-slate-900",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🕶️🏍️🚨",
        tagline: "Je reviendrai."
      },
      {
        id: "terminator-2",
        title: "Terminator 2 : Le Jugement dernier",
        year: 1991,
        duration: "137 min",
        rating: "8.6",
        director: "James Cameron",
        cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick"],
        genre: ["Science Fiction", "Action"],
        description: "Un reprogrammé T-800 musclé est envoyé par la résistance humaine pour protéger l'enfance turbulente de John Connor contre un nouveau cyborg à métal liquide hautement avancé et presque indestructible : le T-1000.",
        gradient: "from-blue-950 via-zinc-900 to-amber-950/10",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🕶️🧪⛓️",
        tagline: "Hasta la vista, baby."
      },
      {
        id: "terminator-3",
        title: "Terminator 3 : Le Soulèvement des machines",
        year: 2003,
        duration: "109 min",
        rating: "6.3",
        director: "Jonathan Mostow",
        cast: ["Arnold Schwarzenegger", "Nick Stahl", "Claire Danes", "Kristanna Loken"],
        genre: ["Science Fiction", "Action"],
        description: "John Connor vit désormais tapi à l'écart du monde pour échapper à toute menace. Malheureusement, Skynet parvient à envoyer la redoutable T-X, un agent assassin surpuissant, tandis qu'un T-850 vieillissant fait barrage.",
        gradient: "from-neutral-900 via-stone-900 to-red-950/30",
        accentColor: "text-red-400 border-red-400/30 bg-red-400/10",
        accentHex: "#f87171",
        symbol: "🔌💥👩‍🎤",
        tagline: "Le réveil de la fin du monde."
      },
      {
        id: "terminator-4",
        title: "Terminator Salvation",
        year: 2009,
        duration: "115 min",
        rating: "6.5",
        director: "McG",
        cast: ["Christian Bale", "Sam Worthington", "Moon Bloodgood", "Helena Bonham Carter"],
        genre: ["Science Fiction", "Action", "War"],
        description: "En 2018, après le cataclysme du Jugement Dernier, John Connor mène avec acharnement la résistance humaine. Il est confronté à Marcus Wright, un mystérieux condamné à mort cybernétique persuadé d'être resté humain.",
        gradient: "from-neutral-900 via-stone-950 to-neutral-800",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "🛩️⚙️🤖",
        tagline: "Le début de la fin pour Skynet."
      },
      {
        id: "terminator-5",
        title: "Terminator Genisys",
        year: 2015,
        duration: "126 min",
        rating: "6.3",
        director: "Alan Taylor",
        cast: ["Arnold Schwarzenegger", "Jason Clarke", "Emilia Clarke", "Jai Courtney"],
        genre: ["Science Fiction", "Action"],
        description: "En envoyant Kyle Reese en 1984 pour sauver Sarah, John déclenche une distorsion temporelle. Reese atterrit ainsi dans un passé fracturé où Sarah Connor, élevée par un T-800 protecteur, est déjà une combattante aguerrie.",
        gradient: "from-indigo-950/30 via-neutral-900 to-slate-950",
        accentColor: "text-purple-400 border-purple-400/30 bg-purple-400/10",
        accentHex: "#c084fc",
        symbol: "🧭🌀🛡️",
        tagline: "Réinitialisez le futur."
      },
      {
        id: "terminator-6",
        title: "Terminator: Dark Fate",
        year: 2019,
        duration: "128 min",
        rating: "6.2",
        director: "Tim Miller",
        cast: ["Linda Hamilton", "Arnold Schwarzenegger", "Mackenzie Davis", "Natalia Reyes"],
        genre: ["Science Fiction", "Action"],
        description: "Près de trente ans après le salut mondial mené par Sarah Connor, une humaine augmentée débarque pour escorter une jeune ouvrière mexicaine traquée par un prototype de Terminator ultra-avancé séparable, le Rev-9.",
        gradient: "from-zinc-900 via-neutral-900 to-rose-950/20",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "🌪️💀🔫",
        tagline: "Bienvenue au lendemain du jour fatidique."
      }
    ]
  },
  {
    id: "fast-and-furious",
    title: "Fast and Furious",
    description: "Speed, big engines, family and spectacular stunts. The complete legendary action saga led by Vin Diesel and Paul Walker, and propelled to glory by prodigy director Justin Lin.",
    movies: [
      {
        id: "fast-1",
        title: "Fast & Furious",
        year: 2001,
        duration: "106 min",
        rating: "6.8",
        director: "Rob Cohen",
        cast: ["Vin Diesel", "Paul Walker", "Michelle Rodriguez", "Jordana Brewster"],
        genre: ["Action", "Thriller"],
        description: "Un flic infiltré de Los Angeles pénètre le milieu des courses de rue nocturnes à hauts risques pour démanteler un gang d'audacieux braqueurs de camions.",
        gradient: "from-neutral-900 via-orange-950/45 to-neutral-950",
        accentColor: "text-orange-400 border-orange-500/30 bg-orange-500/10",
        accentHex: "#fb923c",
        symbol: "🚗💨🔥",
        tagline: "Si vous avez ce qu'il faut, vous pouvez tout avoir."
      },
      {
        id: "fast-2",
        title: "2 Fast 2 Furious",
        year: 2003,
        duration: "107 min",
        rating: "5.9",
        director: "John Singleton",
        cast: ["Paul Walker", "Tyrese Gibson", "Eva Mendes", "Cole Hauser"],
        genre: ["Action", "Thriller"],
        description: "Brian O'Conner fait équipe avec son ami d'enfance Roman Pearce pour faire tomber un parrain de la drogue à Miami en échange du blanchiment de leur casier.",
        gradient: "from-neutral-900 via-blue-950/45 to-neutral-950",
        accentColor: "text-blue-400 border-blue-500/30 bg-blue-500/10",
        accentHex: "#60a5fa",
        symbol: "⚡🏙️🏎️",
        tagline: "Trop rapide pour la police, trop furieux pour le monde."
      },
      {
        id: "fast-3",
        title: "The Fast and the Furious: Tokyo Drift",
        year: 2006,
        duration: "104 min",
        rating: "6.0",
        director: "Justin Lin",
        cast: ["Lucas Black", "Bow Wow", "Sung Kang", "Brian Tee"],
        genre: ["Action", "Thriller"],
        description: "Envoyé à Tokyo chez son père, Sean Boswell s'immerge dans l'univers clandestin et hyper-stylisé du drift de rue japonais.",
        gradient: "from-neutral-900 via-red-950/45 to-amber-950/20",
        accentColor: "text-red-400 border-red-400/30 bg-red-400/10",
        accentHex: "#f87171",
        symbol: "🇯🇵🌀🏁",
        tagline: "Bienvenue dans le berceau de la glisse."
      },
      {
        id: "fast-4",
        title: "Fast & Furious 4",
        year: 2009,
        duration: "107 min",
        rating: "6.5",
        director: "Justin Lin",
        cast: ["Vin Diesel", "Paul Walker", "Michelle Rodriguez", "Jordana Brewster"],
        genre: ["Action", "Thriller"],
        description: "De retour à Los Angeles, Dominic Toretto et l'agent Brian O'Conner s'associent pour infiltrer de l'intérieur un impitoyable cartel mexicain de drogue.",
        gradient: "from-neutral-900 via-zinc-800/40 to-neutral-950",
        accentColor: "text-zinc-300 border-zinc-700 bg-zinc-800/10",
        accentHex: "#d4d4d8",
        symbol: "🏜️🔧💪",
        tagline: "Nouveau modèle. Pièces d'origine."
      },
      {
        id: "fast-5",
        title: "Fast Five",
        year: 2011,
        duration: "130 min",
        rating: "7.3",
        director: "Justin Lin",
        cast: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Jordana Brewster"],
        genre: ["Action", "Thriller"],
        description: "Toretto et sa famille de pilotes préparent le casse ultime de 100 millions de dollars à Rio, pourchassés par le colossal agent Luke Hobbs.",
        gradient: "from-neutral-900 via-amber-955/45 to-neutral-950",
        accentColor: "text-amber-400 border-amber-500/30 bg-amber-500/10",
        accentHex: "#fbbf24",
        symbol: "🇧🇷🪙🚔",
        tagline: "La vitesse a son prix. La famille n'en a pas."
      },
      {
        id: "fast-6",
        title: "Fast & Furious 6",
        year: 2013,
        duration: "130 min",
        rating: "7.0",
        director: "Justin Lin",
        cast: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Michelle Rodriguez"],
        genre: ["Action", "Thriller"],
        description: "L'agent Hobbs sollicite l'aide de l'équipe de Toretto pour traquer des mercenaires à Londres en échange de l'annulation complète de tous leurs délits.",
        gradient: "from-neutral-900 via-indigo-955/45 to-neutral-950",
        accentColor: "text-indigo-400 border-indigo-400/30 bg-indigo-400/10",
        accentHex: "#818cf8",
        symbol: "🇬🇧✈️💥",
        tagline: "Tous les chemins mènent au même carrefour."
      },
      {
        id: "fast-7",
        title: "Furious 7",
        year: 2015,
        duration: "137 min",
        rating: "7.1",
        director: "James Wan",
        cast: ["Vin Diesel", "Paul Walker", "Dwayne Johnson", "Jason Statham"],
        genre: ["Action", "Thriller"],
        description: "L'équipe fait face à Deckard Shaw, un assassin impitoyable assoiffé de vengeance bien décidé à éliminer la famille Toretto, un par un.",
        gradient: "from-neutral-900 via-rose-955/45 to-stone-900",
        accentColor: "text-rose-450 border-rose-450/30 bg-rose-450/10",
        accentHex: "#f43f5e",
        symbol: "🏙️🪂🥀",
        tagline: "Un dernier tour de piste pour la légende de Paul."
      },
      {
        id: "fast-8",
        title: "Fast & Furious 8",
        year: 2017,
        duration: "136 min",
        rating: "6.6",
        director: "F. Gary Gray",
        cast: ["Vin Diesel", "Dwayne Johnson", "Charlize Theron", "Jason Statham"],
        genre: ["Action", "Thriller"],
        description: "Une cyber-terroriste mystérieuse manipule Dom pour qu'il trahisse sa propre famille, forçant l'équipe de survivants à coopérer avec Deckard Shaw.",
        gradient: "from-neutral-900 via-cyan-955/45 to-neutral-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "❄️🛰️🛥️",
        tagline: "Ne jamais tourner le dos à la famille."
      },
      {
        id: "fast-9",
        title: "Fast & Furious 9",
        year: 2021,
        duration: "143 min",
        rating: "5.2",
        director: "Justin Lin",
        cast: ["Vin Diesel", "Michelle Rodriguez", "John Cena", "Tyrese Gibson"],
        genre: ["Action", "Thriller"],
        description: "Dom doit faire face aux secrets douloureux de son passé lorsque son frère Jakob, renié depuis longtemps et assassin de choc, reparaît.",
        gradient: "from-neutral-900 via-emerald-955/45 to-neutral-950",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "🧲🚀🏔️",
        tagline: "La justice accélère."
      },
      {
        id: "fast-10",
        title: "Fast X",
        year: 2023,
        duration: "141 min",
        rating: "5.8",
        director: "Louis Leterrier",
        cast: ["Vin Diesel", "Michelle Rodriguez", "Jason Momoa", "John Cena"],
        genre: ["Action", "Thriller"],
        description: "L'équipe de Dom est la cible de Dante Reyes, le fils rancunier d'un défunt baron de la drogue brésilien bien décidé à détruire tout ce à quoi Dom tient.",
        gradient: "from-neutral-905 via-teal-955/45 to-slate-900",
        accentColor: "text-teal-400 border-teal-400/30 bg-teal-400/10",
        accentHex: "#2dd4bf",
        symbol: "💥💣🏛️",
        tagline: "La fin du chemin commence."
      }
    ]
  },
  {
    id: "mafia-movies",
    title: "Mafia",
    description: "The world of the underworld, goodfellas and cartels. Epic tales of power, loyalty and betrayal.",
    movies: [
      {
        id: "godfather-1",
        title: "The Godfather",
        year: 1972,
        duration: "175 min",
        rating: "9.2",
        director: "Francis Ford Coppola",
        cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
        genre: ["Crime", "Drama"],
        description: "Le patriarche vieillissant d'une dynastie du crime organisé transfère le contrôle de son empire clandestin à son fils réticent.",
        gradient: "from-amber-950 via-stone-900 to-black",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🌹🥃🔫",
        tagline: "Une offre qu'on ne peut pas refuser."
      },
      {
        id: "goodfellas",
        title: "Goodfellas",
        year: 1990,
        duration: "145 min",
        rating: "8.7",
        director: "Martin Scorsese",
        cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
        genre: ["Biography", "Crime", "Drama"],
        description: "L'histoire de Henry Hill et de sa vie au sein de la mafia, couvrant sa relation avec sa femme Karen Hill et ses partenaires mafieux Jimmy Conway et Tommy DeVito.",
        gradient: "from-red-950 via-neutral-900 to-stone-950",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🍝🔫🚁",
        tagline: "Aussi loin que je me souvienne, j'ai toujours voulu être un gangster."
      },
      {
        id: "scarface",
        title: "Scarface",
        year: 1983,
        duration: "170 min",
        rating: "8.3",
        director: "Brian De Palma",
        cast: ["Al Pacino", "Michelle Pfeiffer", "Steven Bauer", "Mary Elizabeth Mastrantonio"],
        genre: ["Crime", "Drama"],
        description: "En 1980, un immigrant cubain arrive à Miami sans rien et finit par devenir un puissant caïd de la drogue.",
        gradient: "from-slate-900 via-rose-950/40 to-black",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "💰🌴🔫",
        tagline: "Le monde est à toi."
      },
    {
        id: "godfather-2",
        title: "The Godfather Part II",
        year: 1974,
        duration: "202 min",
        rating: "9.0",
        director: "Francis Ford Coppola",
        cast: ["Al Pacino", "Robert De Niro", "Robert Duvall", "Diane Keaton"],
        genre: ["Crime", "Drama"],
        description: "L'histoire de la famille Corleone continue avec Vito Corleone construisant son empire et Michael Corleone le gérant dans les années 1950.",
        gradient: "from-amber-950 via-stone-900 to-black",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🌹🥃🔫",
        tagline: "Gardez vos amis proches, mais vos ennemis encore plus proches."
      },
      {
        id: "godfather-3",
        title: "The Godfather Part III",
        year: 1990,
        duration: "162 min",
        rating: "7.6",
        director: "Francis Ford Coppola",
        cast: ["Al Pacino", "Diane Keaton", "Andy Garcia", "Talia Shire"],
        genre: ["Crime", "Drama"],
        description: "Michael Corleone tente de légitimer les affaires de sa famille, mais est rattrapé par les péchés de son passé.",
        gradient: "from-amber-950 via-stone-900 to-black",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🌹🥃🔫",
        tagline: "Juste au moment où je pensais être dehors... ils me ramènent dedans."
      },
      {
        id: "irishman",
        title: "The Irishman",
        year: 2019,
        duration: "209 min",
        rating: "7.8",
        director: "Martin Scorsese",
        cast: ["Robert De Niro", "Al Pacino", "Joe Pesci", "Harvey Keitel"],
        genre: ["Biography", "Crime", "Drama"],
        description: "Frank Sheeran, un ancien combattant de la Seconde Guerre mondiale, escroc et tueur à gages, revient sur son passé.",
        gradient: "from-zinc-900 via-neutral-900 to-stone-950",
        accentColor: "text-zinc-400 border-zinc-400/30 bg-zinc-400/10",
        accentHex: "#a1a1aa",
        symbol: "🇮🇪🔫👴",
        tagline: "J'ai entendu dire que tu peignais des maisons."
      },
      {
        id: "american-gangster",
        title: "American Gangster",
        year: 2007,
        duration: "157 min",
        rating: "7.8",
        director: "Ridley Scott",
        cast: ["Denzel Washington", "Russell Crowe", "Chiwetel Ejiofor", "Josh Brolin"],
        genre: ["Biography", "Crime", "Drama"],
        description: "Un flic de New York est chargé de faire tomber le plus grand baron de la drogue de la ville.",
        gradient: "from-stone-900 via-neutral-900 to-black",
        accentColor: "text-stone-400 border-stone-400/30 bg-stone-400/10",
        accentHex: "#a8a29e",
        symbol: "🚔❄️💰",
        tagline: "Il y a des flics pourris, et des gangsters honnêtes."
      },
      {
        id: "casino",
        title: "Casino",
        year: 1995,
        duration: "178 min",
        rating: "8.2",
        director: "Martin Scorsese",
        cast: ["Robert De Niro", "Sharon Stone", "Joe Pesci", "James Woods"],
        genre: ["Crime", "Drama"],
        description: "L'histoire de l'ambition aveugle et de la cupidité qui ont mené à la chute d'un empire du jeu mafieux.",
        gradient: "from-yellow-950 via-stone-900 to-black",
        accentColor: "text-yellow-500 border-yellow-500/30 bg-yellow-500/10",
        accentHex: "#eab308",
        symbol: "🎰🎲💼",
        tagline: "Personne ne reste éternellement au sommet."
      }
    ]
  },
  {
    id: "mind-bending-mysteries",
    title: "Mysteries",
    description: "Chilling psychological thrillers, sordid murders and twists that will leave you speechless.",
    movies: [
      {
        id: "se7en",
        title: "Se7en",
        year: 1995,
        duration: "127 min",
        rating: "8.6",
        director: "David Fincher",
        cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey"],
        genre: ["Crime", "Drama", "Mystery"],
        description: "Deux détectives, un vétéran et une recrue, traquent un tueur en série dont les crimes sont basés sur les sept péchés capitaux.",
        gradient: "from-stone-900 via-yellow-950/20 to-black",
        accentColor: "text-stone-400 border-stone-400/30 bg-stone-400/10",
        accentHex: "#a8a29e",
        symbol: "📦🌧️🔍",
        tagline: "Qu'est-ce qu'il y a dans la boîte ?"
      },
      {
        id: "memento",
        title: "Memento",
        year: 2000,
        duration: "113 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano", "Mark Boone Junior"],
        genre: ["Mystery", "Thriller"],
        description: "Un homme souffrant d'amnésie antérograde (perte de la mémoire à court terme) utilise des notes et des tatouages pour traquer le meurtrier de sa femme.",
        gradient: "from-slate-900 via-indigo-950/30 to-black",
        accentColor: "text-indigo-400 border-indigo-400/30 bg-indigo-400/10",
        accentHex: "#818cf8",
        symbol: "📸🖊️🧠",
        tagline: "Certains souvenirs sont meilleurs oubliés."
      },
      {
        id: "zodiac",
        title: "Zodiac",
        year: 2007,
        duration: "157 min",
        rating: "7.7",
        director: "David Fincher",
        cast: ["Jake Gyllenhaal", "Robert Downey Jr.", "Mark Ruffalo", "Anthony Edwards"],
        genre: ["Crime", "Drama", "Mystery"],
        description: "L'histoire vraie de la traque du tueur du Zodiaque, un meurtrier en série qui terrorisa la baie de San Francisco à la fin des années 60 et 70.",
        gradient: "from-stone-950 via-zinc-900 to-black",
        accentColor: "text-zinc-400 border-zinc-400/30 bg-zinc-400/10",
        accentHex: "#a1a1aa",
        symbol: "🗞️🕵️‍♂️✉️",
        tagline: "Il n'y a pas de fin à l'obsession."
      },
      {
        id: "prisoners",
        title: "Prisoners",
        year: 2013,
        duration: "153 min",
        rating: "8.1",
        director: "Denis Villeneuve",
        cast: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Maria Bello"],
        genre: ["Crime", "Drama", "Mystery"],
        description: "Lorsque la fille de Keller Dover est kidnappée avec son amie, il prend les choses en main alors que la police explore de multiples pistes sans succès.",
        gradient: "from-neutral-950 via-stone-900 to-black",
        accentColor: "text-stone-300 border-stone-300/30 bg-stone-300/10",
        accentHex: "#d6d3d1",
        symbol: "❄️🚐🔎",
        tagline: "Chaque moment compte."
      }
    ]
  },
  {
    id: "the-batman",
    title: "The Batman",
    description: "The Dark Knight defends Gotham City against crime and corruption.",
    movies: [
      {
        id: "batman-begins",
        title: "Batman Begins",
        year: 2005,
        duration: "140 min",
        rating: "8.2",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Michael Caine", "Liam Neeson", "Katie Holmes"],
        genre: ["Action", "Crime", "Drama"],
        description: "Après s'être entraîné avec son mentor, Bruce Wayne entame son combat pour libérer Gotham City de la corruption.",
        gradient: "from-zinc-950 via-neutral-900 to-black",
        accentColor: "text-zinc-500 border-zinc-500/30 bg-zinc-500/10",
        accentHex: "#71717a",
        symbol: "🦇🌃🥷",
        tagline: "Le mythe commence."
      },
      {
        id: "the-dark-knight",
        title: "The Dark Knight",
        year: 2008,
        duration: "152 min",
        rating: "9.0",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
        genre: ["Action", "Crime", "Drama"],
        description: "Lorsque la menace connue sous le nom du Joker sème le chaos sur les habitants de Gotham, Batman doit accepter l'un des plus grands tests psychologiques et physiques de sa capacité à combattre l'injustice.",
        gradient: "from-zinc-900 via-neutral-900 to-black",
        accentColor: "text-purple-500 border-purple-500/30 bg-purple-500/10",
        accentHex: "#a855f7",
        symbol: "🦇🃏🔥",
        tagline: "Pourquoi cet air si sérieux ?"
      },
      {
        id: "the-dark-knight-rises",
        title: "The Dark Knight Rises",
        year: 2012,
        duration: "164 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"],
        genre: ["Action", "Crime", "Drama"],
        description: "Huit ans après les événements du Joker, le terroriste Bane force Bruce Wayne à reprendre du service en tant que Batman.",
        gradient: "from-stone-900 via-neutral-900 to-black",
        accentColor: "text-stone-400 border-stone-400/30 bg-stone-400/10",
        accentHex: "#a8a29e",
        symbol: "🦇💪🔥",
        tagline: "La fin d'une légende."
      },
      {
        id: "the-batman-2022",
        title: "The Batman",
        year: 2022,
        duration: "176 min",
        rating: "7.8",
        director: "Matt Reeves",
        cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Colin Farrell"],
        genre: ["Action", "Crime", "Drama"],
        description: "Lorsqu'un tueur en série s'attaque à l'élite de Gotham avec une série d'intrigues sadiques, une piste d'indices cryptiques envoie le plus grand détective du monde dans une enquête.",
        gradient: "from-red-950/40 via-neutral-900 to-black",
        accentColor: "text-red-600 border-red-600/30 bg-red-600/10",
        accentHex: "#dc2626",
        symbol: "🦇❓🌧️",
        tagline: "Démasquez la vérité."
      }
    ]
  }
];
