export interface Movie {
  id: string;
  title: string;
  year: number;
  duration: string;
  rating: string;
  director: string;
  cast: string[];
  castDetails?: { id: string; name: string; role?: string; imageUrl?: string; }[];
  genre: string[];
  description?: string;
  gradient?: string; // Tailwind gradient colors e.g., 'from-slate-900 to-indigo-950'
  accentColor?: string; // Tailwind text/border e.g., 'text-indigo-400 font-bold border-indigo-400'
  accentHex?: string; // Hex code for custom badges and glows
  symbol?: string; // Emoji symbols reflecting theme for graphic poster layout
  tagline?: string;
  streamUrl?: string;
  posterUrl?: string;
  backdropUrl?: string;
  isIframeEmbed?: boolean;
  iframeSrc?: string;
  isCatalog?: boolean;
  originalTitle?: string;
  studios?: string[];
  providerIds?: Record<string, string>;
}

export interface Collection {
  id: string;
  title: string;
  description: string;
  movies: Movie[];
}

export const COLLECTIONS: Collection[] = [
  {
    id: "comedy-gold",
    title: "Best Comedy Gold",
    description: "The most hilarious, iconic, and rewatchable comedy masterpieces of all time.",
    movies: [
      {
        id: "21-jump-street",
        title: "21 Jump Street",
        posterUrl: "https://image.tmdb.org/t/p/w500/q3UeqQ2I3L1m6K0rL6W3d8wP9E1.jpg",
        year: 2012,
        duration: "109 min",
        rating: "7.2",
        director: "Phil Lord, Christopher Miller",
        cast: ["Jonah Hill", "Channing Tatum", "Ice Cube"],
        genre: ["Action", "Comedy", "Crime"],
      },
      {
        id: "22-jump-street",
        title: "22 Jump Street",
        posterUrl: "https://image.tmdb.org/t/p/w500/40wV3Y8JbT97U0oF9R5TiyA4LqA.jpg",
        year: 2014,
        duration: "112 min",
        rating: "7.0",
        director: "Phil Lord, Christopher Miller",
        cast: ["Jonah Hill", "Channing Tatum", "Ice Cube"],
        genre: ["Action", "Comedy", "Crime"],
      },
      {
        id: "superbad",
        title: "Superbad",
        posterUrl: "https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2VNqjv6V1W1J3iA.jpg",
        year: 2007,
        duration: "113 min",
        rating: "7.6",
        director: "Greg Mottola",
        cast: ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse"],
        genre: ["Comedy"],
      },
      {
        id: "grown-ups",
        title: "Grown Ups",
        posterUrl: "https://image.tmdb.org/t/p/w500/q7k7eJ7ZkYk5E9Zf8D4bZ6fP6O5.jpg",
        year: 2010,
        duration: "102 min",
        rating: "5.9",
        director: "Dennis Dugan",
        cast: ["Adam Sandler", "Kevin James", "Chris Rock"],
        genre: ["Comedy"],
      },
      {
        id: "white-chicks",
        title: "White Chicks",
        posterUrl: "https://image.tmdb.org/t/p/w500/vXvU2wB5T7u2i6E5F8M4b0u4Q5Q.jpg",
        year: 2004,
        duration: "109 min",
        rating: "5.8",
        director: "Keenen Ivory Wayans",
        cast: ["Marlon Wayans", "Shawn Wayans", "Busy Philipps"],
        genre: ["Comedy", "Crime"],
      }
    ]
  },


  {
    id: "trending-now",
    title: "TRENDING NOW",
    description: "The most watched and highly anticipated movies right now.",
    movies: [
      {
        id: "obsession",
        title: "Obsession",
        year: 2025,
        duration: "115 min",
        rating: "8.1",
        director: "Unknown",
        cast: [],
        genre: ["Thriller"],
        description: "A gripping tale of obsession and consequence.",
        gradient: "from-slate-900 via-neutral-900 to-rose-950/40",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "🔥",
        tagline: "Desire has a price."
      },
      
      {
        id: "backrooms",
        title: "Backrooms",
        year: 2025,
        duration: "105 min",
        rating: "7.5",
        director: "Kane Parsons",
        cast: [],
        genre: ["Horror", "Sci-Fi"],
        description: "Trapped in an endless maze of office rooms, survival is not guaranteed.",
        gradient: "from-slate-900 via-neutral-900 to-yellow-950/40",
        accentColor: "text-yellow-500 border-yellow-500/30 bg-yellow-500/10",
        accentHex: "#eab308",
        symbol: "🚪",
        tagline: "Don't clip out of reality."
      },
      {
        id: "michael",
        title: "Michael",
        year: 2025,
        duration: "130 min",
        rating: "8.5",
        director: "Antoine Fuqua",
        cast: ["Jaafar Jackson"],
        genre: ["Biography", "Music", "Drama"],
        description: "The life and legacy of the King of Pop, Michael Jackson.",
        gradient: "from-slate-900 via-neutral-900 to-blue-950/40",
        accentColor: "text-blue-500 border-blue-500/30 bg-blue-500/10",
        accentHex: "#3b82f6",
        symbol: "🎤",
        tagline: "The King of Pop."
      },
      {
        id: "devil-wears-prada-2",
        title: "The Devil Wears Prada 2",
        year: 2025,
        duration: "120 min",
        rating: "N/A",
        director: "Unknown",
        cast: [],
        genre: ["Comedy", "Drama"],
        description: "The highly anticipated sequel.",
        gradient: "from-slate-900 via-neutral-900 to-fuchsia-950/40",
        accentColor: "text-fuchsia-500 border-fuchsia-500/30 bg-fuchsia-500/10",
        accentHex: "#d946ef",
        symbol: "👠",
        tagline: "She's back."
      },
      {
        id: "the-matrix",
        title: "The Matrix",
        year: 1999,
        duration: "136 min",
        rating: "8.7",
        director: "The Wachowskis",
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
        genre: ["Sci-Fi", "Action"],
        description: "A computer hacker learns from mysterious rebels about the true nature of his reality.",
        gradient: "from-slate-900 via-neutral-900 to-green-950/40",
        accentColor: "text-green-500 border-green-500/30 bg-green-500/10",
        accentHex: "#22c55e",
        symbol: "💊",
        tagline: "Welcome to the Real World."
      }
    ]
  },

  
  {
    id: "indiana-jones",
    title: "Indiana Jones",
    description: "The whip, the hat and the mysteries of history. Follow the greatest archaeologist-adventurer of all time.",
    movies: [
      {
        id: "indy-1",
        title: "Raiders of the Lost Ark",
        year: 1981,
        duration: "115 min",
        rating: "8.4",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Karen Allen", "Paul Freeman", "John Rhys-Davies"],
        genre: ["Adventure", "Action"],
        description: "Indy is tasked with a perilous mission by US intelligence: to find the Ark of the Covenant, a chest containing the Tablets of the Law, coveted by the Nazis for its supposed military invincibility.",
        gradient: "from-neutral-900 via-amber-950/30 to-amber-950/40",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🤠📜🏺",
        tagline: "The quest for the impossible starts here."
      },
      {
        id: "indy-2",
        title: "Indiana Jones and the Temple of Doom",
        year: 1984,
        duration: "118 min",
        rating: "7.5",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Kate Capshaw", "Ke Huy Quan", "Amrish Puri"],
        genre: ["Adventure", "Action"],
        description: "In India, Indiana Jones, a clever young boy named Short Round, and a cabaret singer find themselves in an impoverished village. The locals beg them to retrieve a sacred mystical stone stolen by a bloodthirsty cult.",
        gradient: "from-neutral-900 via-red-950/30 to-amber-950/40",
        accentColor: "text-red-400 border-red-400/30 bg-red-400/10",
        accentHex: "#f87171",
        symbol: "🏮🛒💎",
        tagline: "An adventure of absolute mystical darkness."
      },
      {
        id: "indy-3",
        title: "Indiana Jones and the Last Crusade",
        year: 1989,
        duration: "127 min",
        rating: "8.2",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Sean Connery", "Alison Doody", "Denholm Elliott"],
        genre: ["Adventure", "Action"],
        description: "Indiana Jones sets out on the trail of his father, Professor Henry Jones, who mysteriously disappeared while searching for the legendary Holy Grail. Together, father and son unite to overcome millennial trials.",
        gradient: "from-neutral-900 via-amber-950/30 to-yellow-950/40",
        accentColor: "text-yellow-500 border-yellow-500/30 bg-yellow-500/10",
        accentHex: "#eab308",
        symbol: "🏆🛡️⚔️",
        tagline: "The Grail only awaits pure hearts."
      },
      {
        id: "indy-4",
        title: "Indiana Jones et le Royaume du Crâne de Cristal",
        year: 2008,
        duration: "122 min",
        rating: "6.2",
        director: "Steven Spielberg",
        cast: ["Harrison Ford", "Cate Blanchett", "Shia LaBeouf", "Karen Allen"],
        genre: ["Adventure", "Science Fiction"],
        description: "In 1957, during the Cold War, Indiana Jones becomes entangled in a Soviet plot to uncover the secret behind a mysterious crystal skull discovered in the Amazon.",
        gradient: "from-neutral-900 via-emerald-950/30 to-teal-950/40",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "👽💀🌴",
        tagline: "The secret of the Amazon transcends our world."
      },
      {
        id: "indy-5",
        title: "Indiana Jones et le Cadran de la Destinée",
        year: 2023,
        duration: "154 min",
        rating: "6.6",
        director: "James Mangold",
        cast: ["Harrison Ford", "Phoebe Waller-Bridge", "Mads Mikkelsen", "Antonio Banderas"],
        genre: ["Adventure", "Action"],
        description: "In 1969, against the backdrop of the space race, the famous archaeologist prepares to retire. But the appearance of his goddaughter Helena and a former Nazi working for NASA plunges him back into a race against time.",
        gradient: "from-neutral-900 via-yellow-950/20 to-stone-900",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "⚙️🕰️✈️",
        tagline: "Against time, the ultimate journey begins."
      }
    ]
  },
  {
    id: "tarantino-collection",
    title: "Quentin Tarantino",
    description: "Punchy dialogue, stylized violence and unforgettable soundtracks. The unique work of master Quentin Tarantino.",
    movies: [
      {
        id: "pulp-fiction",
        title: "Pulp Fiction",
        year: 1994,
        duration: "154 min",
        rating: "8.9",
        director: "Quentin Tarantino",
        cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
        genre: ["Crime", "Drama"],
        description: "The bloody, comical and dramatic odyssey of two talkative hitmen, a fading boxer, the seductive wife of a mob boss and two amateur robbers in a local diner.",
        gradient: "from-red-950 via-neutral-900 to-amber-950/40",
        accentColor: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
        accentHex: "#facc15",
        symbol: "💃🍔💼",
        tagline: "Life is not a long quiet river in the land of thugs."
      },
      {
        id: "reservoir-dogs",
        title: "Reservoir Dogs",
        year: 1992,
        duration: "99 min",
        rating: "8.3",
        director: "Quentin Tarantino",
        cast: ["Harvey Keitel", "Tim Roth", "Michael Madsen", "Steve Buscemi"],
        genre: ["Crime", "Thriller"],
        description: "Six professional criminals, who do not know each other, are hired by a mob boss to rob a diamond merchant. The heist turns into a bloody carnage, and the survivors gather in an abandoned warehouse, suspecting a traitor.",
        gradient: "from-stone-900 via-neutral-900 to-red-950/50",
        accentColor: "text-neutral-200 border-neutral-400/30 bg-neutral-400/10",
        accentHex: "#e5e5e5",
        symbol: "🕶️🤵💎",
        tagline: "No real names, no quarter."
      },
      {
        id: "kill-bill-1",
        title: "Kill Bill: Vol. 1",
        year: 2003,
        duration: "111 min",
        rating: "8.2",
        director: "Quentin Tarantino",
        cast: ["Uma Thurman", "Lucy Liu", "Vivica A. Fox", "David Carradine"],
        genre: ["Action", "Crime"],
        description: "During her wedding, a former hitwoman is violently attacked by her former lover and boss, Bill. Waking up from a four-year coma, the Bride has only one goal for survival: exact methodical revenge.",
        gradient: "from-yellow-950 via-neutral-900 to-amber-950/30",
        accentColor: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
        accentHex: "#eab308",
        symbol: "🥻⚔️🩸",
        tagline: "Revenge is a dish best served cold."
      },
      {
        id: "kill-bill-2",
        title: "Kill Bill: Vol. 2",
        year: 2004,
        duration: "137 min",
        rating: "8.0",
        director: "Quentin Tarantino",
        cast: ["Uma Thurman", "David Carradine", "Michael Madsen", "Daryl Hannah"],
        genre: ["Action", "Crime"],
        description: "After eliminating her first targets, the Bride continues her relentless revenge against Budd and Elle Driver. Her final and inevitable confrontation with her mentor and tormentor, Bill, is approaching.",
        gradient: "from-amber-950 via-neutral-900 to-stone-950",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "🐍🥋🎯",
        tagline: "The final chapter of her blacklist."
      },
      {
        id: "inglourious-basterds",
        title: "Inglourious Basterds",
        year: 2009,
        duration: "153 min",
        rating: "8.3",
        director: "Quentin Tarantino",
        cast: ["Brad Pitt", "Mélanie Laurent", "Christoph Waltz", "Michael Fassbender"],
        genre: ["War", "Drama", "Action"],
        description: "In occupied France, a young Jewish cinema owner plots an incendiary revenge, while a commando of Jewish-American soldiers, the 'Basterds', spread terror among the occupiers by scalping their enemies.",
        gradient: "from-red-950 via-stone-900 to-neutral-950",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🎦🎖️🪓",
        tagline: "An explosive rewrite of great history."
      },
      {
        id: "django-unchained",
        title: "Django Unchained",
        year: 2012,
        duration: "165 min",
        rating: "8.5",
        director: "Quentin Tarantino",
        cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington"],
        genre: ["Western", "Drama"],
        description: "Two years before the Civil War, Django, a slave, teams up with Dr. King Schultz, an eccentric German bounty hunter. Schultz frees Django and helps him find his wife Broomhilda, held in the plantation of the cruel Calvin Candie.",
        gradient: "from-amber-950 via-neutral-900 to-red-950/40",
        accentColor: "text-amber-400 border-amber-400/30 bg-amber-400/10",
        accentHex: "#fbbf24",
        symbol: "🐎🩸⛓️",
        tagline: "Freedom is not negotiable, it is snatched."
      },
      {
        id: "once-upon-a-time",
        title: "Once Upon a Time in Hollywood",
        year: 2019,
        duration: "161 min",
        rating: "7.6",
        director: "Quentin Tarantino",
        cast: ["Leonardo DiCaprio", "Brad Pitt", "Margot Robbie", "Emile Hirsch"],
        genre: ["Drama", "Comedy"],
        description: "In 1969 of the Hollywood Golden Age, Rick Dalton, a fading star of western TV series, and Cliff Booth, his impassive longtime stunt double, wander in a world they no longer recognize.",
        gradient: "from-yellow-950/40 via-neutral-900 to-amber-950/40",
        accentColor: "text-amber-300 border-amber-300/30 bg-amber-300/10",
        accentHex: "#fde047",
        symbol: "🎬🎙️🐕",
        tagline: "A melancholic and flamboyant fairy tale about cinema."
      },
      {
        id: "the-hateful-eight",
        title: "The Hateful Eight",
        year: 2015,
        duration: "168 min",
        rating: "7.8",
        director: "Quentin Tarantino",
        cast: ["Samuel L. Jackson", "Kurt Russell", "Jennifer Jason Leigh", "Walton Goggins"],
        genre: ["Western", "Crime", "Mystère"],
        description: "A few years after the Civil War, a renowned bounty hunter and his prisoner are stranded by a terrible mountain blizzard in a stagecoach refuge alongside six suspects of a conspiracy.",
        gradient: "from-stone-900 via-zinc-900 to-blue-950/30",
        accentColor: "text-sky-300 border-sky-300/30 bg-sky-300/10",
        accentHex: "#7dd3fc",
        symbol: "❄️🛖🥃",
        tagline: "Eight liars. None will escape unscathed."
      }
    ]
  },
  {
    id: "christopher-nolan",
    title: "Christopher Nolan",
    description: "Distorted time, fragmented reality and visions of unparalleled scale. The conceptual cinema of Christopher Nolan.",
    movies: [
      {
        id: "inception",
        title: "Inception",
        year: 2010,
        duration: "148 min",
        rating: "8.8",
        director: "Christopher Nolan",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
        genre: ["Science Fiction", "Action", "Thriller"],
        description: "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state. To get his life back, he must do the impossible: inception.",
        gradient: "from-indigo-950 via-slate-900 to-slate-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🌀🌀🎲",
        tagline: "Your mind is the scene of the crime."
      },
      {
        id: "interstellar",
        title: "Interstellar",
        year: 2014,
        duration: "169 min",
        rating: "8.7",
        director: "Christopher Nolan",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        genre: ["Science Fiction", "Drama", "Adventure"],
        description: "As Earth slowly dies, a group of intrepid astronauts and engineers travel through a newly discovered wormhole in an attempt to find a habitable planet to save humanity.",
        gradient: "from-blue-950 via-indigo-950/50 to-neutral-950",
        backdropUrl: "https://www.wallpaperflare.com/static/536/846/466/interstellar-movie-movies-interstellar-movie-wallpaper.jpg",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "🪐🚀🌾",
        tagline: "Love is the one thing that transcends time and space."
      },
      
      {
        id: "the-dark-knight",
        title: "The Dark Knight",
        year: 2008,
        duration: "152 min",
        rating: "9.0",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
        genre: ["Action", "Crime", "Drama"],
        description: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and DA Harvey Dent. But a sadistically anarchic criminal mastermind known as the Joker plunges the city into chaos.",
        gradient: "from-blue-950/30 via-neutral-900 to-stone-950",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🃏🔥🌃",
        tagline: "Why so serious?"
      },
      {
        id: "the-dark-knight-rises",
        title: "The Dark Knight Rises",
        year: 2012,
        duration: "164 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"],
        genre: ["Action", "Thriller"],
        description: "Eight years after the death of Harvey Dent, Batman has vanished from Gotham. However, the appearance of a cunning cat burglar and a ruthless terrorist named Bane forces Bruce Wayne out of his long physical exile.",
        gradient: "from-zinc-900 via-slate-900 to-stone-900/50",
        accentColor: "text-slate-400 border-slate-400/30 bg-slate-400/10",
        accentHex: "#94a3b8",
        symbol: "🕸️💥🎙️",
        tagline: "The legend ends in fire."
      },
      {
        id: "dunkirk",
        title: "Dunkirk",
        year: 2017,
        duration: "106 min",
        rating: "7.8",
        director: "Christopher Nolan",
        cast: ["Fionn Whitehead", "Tom Hardy", "Mark Rylance", "Cillian Murphy"],
        genre: ["War", "Drama", "History"],
        description: "In May 1940, some 400,000 Allied soldiers found themselves surrounded and trapped on the beach of Dunkirk by the German army. The most daring naval evacuation in history is organized.",
        gradient: "from-sky-950/30 via-slate-900 to-zinc-900",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "🏖️⚓✈️",
        tagline: "Time is the worst of enemies."
      },
      {
        id: "tenet",
        title: "Tenet",
        year: 2020,
        duration: "150 min",
        rating: "7.3",
        director: "Christopher Nolan",
        cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki", "Kenneth Branagh"],
        genre: ["Science Fiction", "Action", "Espionage"],
        description: "Armed with only one word—Tenet—and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
        gradient: "from-indigo-950 via-neutral-900 to-teal-950/20",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "◀️▶️🚢",
        tagline: "Don't try to understand it, feel it."
      },
      {
        id: "oppenheimer",
        title: "Oppenheimer",
        year: 2023,
        duration: "180 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
        genre: ["Biography", "Drama", "History"],
        description: "Physicist J. Robert Oppenheimer takes the lead on the top-secret Manhattan Project in the New Mexico desert with a group of brilliant scientists to develop the first atomic bomb, forever changing the course of history.",
        gradient: "from-amber-950/50 via-neutral-900 to-stone-950",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "☢️🔬🤯",
        tagline: "Now I am become Death, the destroyer of worlds."
      }
    ]
  },
  {
    id: "star-wars",
    title: "Star Wars",
    description: "The legendary space saga. An eternal struggle between the Force and the Dark Side across the galaxy.",
    movies: [
      {
        id: "sw-1",
        title: "Episode I: The Phantom Menace",
        year: 1999,
        duration: "136 min",
        rating: "6.5",
        director: "George Lucas",
        cast: ["Liam Neeson", "Ewan McGregor", "Natalie Portman", "Jake Lloyd"],
        genre: ["Science Fiction", "Adventure"],
        description: "Two Jedi Knights escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their original glory.",
        gradient: "from-blue-950/30 via-neutral-900 to-amber-950/30",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "🏜️⚔️👹",
        tagline: "The destiny of a galactic prodigy awakens."
      },
      {
        id: "sw-2",
        title: "Episode II: Attack of the Clones",
        year: 2002,
        duration: "142 min",
        rating: "6.6",
        director: "George Lucas",
        cast: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen", "Christopher Lee"],
        genre: ["Science Fiction", "Adventure"],
        description: "Ten years later, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the Senator and discovers a secret clone army crafted for the Jedi.",
        gradient: "from-indigo-950/40 via-neutral-900 to-slate-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🪐🧪🤖",
        tagline: "A forbidden passion in a galaxy on the dawn of conflict."
      },
      {
        id: "sw-3",
        title: "Episode III: Revenge of the Sith",
        year: 2005,
        duration: "140 min",
        rating: "7.6",
        director: "George Lucas",
        cast: ["Ewan McGregor", "Natalie Portman", "Hayden Christensen", "Ian McDiarmid"],
        genre: ["Science Fiction", "Adventure"],
        description: "Three years into the Clone Wars, Anakin Skywalker is torn between his loyalty to the Jedi and the temptations of dark power offered by Chancellor Palpatine to save his wife.",
        gradient: "from-red-950/60 via-neutral-900 to-stone-900",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🌋⚔️💀",
        tagline: "The tragic birth of Darth Vader."
      },
      {
        id: "sw-4",
        title: "Episode IV: A New Hope",
        year: 1977,
        duration: "121 min",
        rating: "8.6",
        director: "George Lucas",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
        genre: ["Science Fiction", "Adventure"],
        description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
        gradient: "from-neutral-900 via-blue-950/30 to-slate-900",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🏜️🚀🔵",
        tagline: "A long time ago, in a galaxy far, far away..."
      },
      {
        id: "sw-5",
        title: "Episode V: The Empire Strikes Back",
        year: 1980,
        duration: "124 min",
        rating: "8.7",
        director: "Irvin Kershner",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"],
        genre: ["Science Fiction", "Adventure"],
        description: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader.",
        gradient: "from-sky-950/40 via-neutral-900 to-slate-950",
        accentColor: "text-sky-400 border-sky-400/30 bg-sky-400/10",
        accentHex: "#38bdf8",
        symbol: "❄️🐸🪐",
        tagline: "The Dark Side reveals itself. A shattering truth."
      },
      {
        id: "sw-6",
        title: "Episode VI: Return of the Jedi",
        year: 1983,
        duration: "131 min",
        rating: "8.3",
        director: "Richard Marquand",
        cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"],
        genre: ["Science Fiction", "Adventure"],
        description: "After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap.",
        gradient: "from-emerald-950/30 via-neutral-900 to-stone-900",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "🌳⚡⚔️",
        tagline: "The final showdown for a father's redemption."
      },
      {
        id: "sw-7",
        title: "Episode VII: The Force Awakens",
        year: 2015,
        duration: "138 min",
        rating: "7.8",
        director: "J.J. Abrams",
        cast: ["Daisy Ridley", "John Boyega", "Oscar Isaac", "Adam Driver"],
        genre: ["Science Fiction", "Adventure"],
        description: "A new threat arises from the ashes of the Empire: the First Order. Rey, a solitary scavenger, teams up with Finn, a deserting stormtrooper, and Han Solo to track down the last Jedi master, Luke Skywalker.",
        gradient: "from-neutral-900 via-zinc-900 to-purple-950/30",
        accentColor: "text-purple-400 border-purple-400/30 bg-purple-400/10",
        accentHex: "#c084fc",
        symbol: "🧭🌅🔵",
        tagline: "A new generation of heroes faces the Dark Side."
      },
      {
        id: "sw-8",
        title: "Episode VIII: The Last Jedi",
        year: 2017,
        duration: "152 min",
        rating: "6.9",
        director: "Rian Johnson",
        cast: ["Daisy Ridley", "John Boyega", "Mark Hamill", "Carrie Fisher"],
        genre: ["Science Fiction", "Adventure"],
        description: "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
        gradient: "from-rose-950/30 via-neutral-900 to-stone-900",
        accentColor: "text-rose-400 border-rose-400/30 bg-rose-400/10",
        accentHex: "#f43f5e",
        symbol: "🪨🦅🔴",
        tagline: "Break the past to rewrite the galactic future."
      },
      {
        id: "sw-9",
        title: "Episode IX: The Rise of Skywalker",
        year: 2019,
        duration: "142 min",
        rating: "6.4",
        director: "J.J. Abrams",
        cast: ["Daisy Ridley", "Adam Driver", "John Boyega", "Oscar Isaac"],
        genre: ["Science Fiction", "Adventure"],
        description: "The surviving members of the resistance face the First Order once again, and the legendary conflict between the Jedi and the Sith reaches its peak bringing the Skywalker saga to its end.",
        gradient: "from-cyan-950/30 via-neutral-900 to-slate-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "⚡🔮🛸",
        tagline: "The glorious end of the great Skywalker saga."
      },
      {
        id: "sw-rogue-one",
        title: "Rogue One: A Star Wars Story",
        year: 2016,
        duration: "133 min",
        rating: "7.8",
        director: "Gareth Edwards",
        cast: ["Felicity Jones", "Diego Luna", "Ben Mendelsohn", "Donnie Yen"],
        genre: ["Science Fiction", "Action", "War"],
        description: "A disparate group of rebels unite for a suicide military intelligence mission: steal the secret plans to the Death Star, the Empire's ultimate weapon of mass destruction.",
        gradient: "from-zinc-900 via-neutral-900 to-slate-950/40",
        accentColor: "text-teal-400 border-teal-400/30 bg-teal-400/10",
        accentHex: "#2dd4bf",
        symbol: "🏖️🚨🎖️",
        tagline: "The daring heist that sparked hope."
      }
    ]
  },
  {
    id: "james-bond",
    title: "James Bond",
    description: "British composure, high-tech gadgets and a license to kill. The greatest missions of the iconic spy.",
    movies: [
      {
        id: "bond-dr-no",
        title: "James Bond contre Dr No",
        year: 1962,
        duration: "110 min",
        rating: "7.2",
        director: "Terence Young",
        cast: ["Sean Connery", "Ursula Andress", "Joseph Wiseman", "Jack Lord"],
        genre: ["Action", "Adventure", "Espionage"],
        description: "A resourceful British government agent seeks answers in a case involving the disappearance of a colleague and the disruption of the American space program.",
        gradient: "from-slate-900 via-neutral-900 to-blue-950/30",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🏝️🦀🤵",
        tagline: "The worldwide introduction of Agent 007."
      },
      {
        id: "bond-goldfinger",
        title: "Goldfinger",
        year: 1964,
        duration: "110 min",
        rating: "7.7",
        director: "Terence Young",
        cast: ["Sean Connery", "Honor Blackman", "Gert Fröbe", "Harold Sakata"],
        genre: ["Action", "Espionage"],
        description: "While investigating a gold magnate's smuggling, James Bond uncovers a plot to contaminate the Fort Knox gold reserve.",
        gradient: "from-stone-900 via-neutral-900 to-amber-950/40",
        accentColor: "text-amber-400 border-amber-400/30 bg-amber-400/10",
        accentHex: "#fbbf24",
        symbol: "👑🚗🪙",
        tagline: "Everything he touches turns to gold."
      },
      {
        id: "bond-casino-royale",
        title: "Casino Royale",
        year: 2006,
        duration: "144 min",
        rating: "8.0",
        director: "Martin Campbell",
        cast: ["Daniel Craig", "Eva Green", "Mads Mikkelsen", "Judi Dench"],
        genre: ["Espionage", "Action", "Thriller"],
        description: "After earning 00 status and a licence to kill, Secret Agent James Bond sets out on his first mission as 007. Bond must defeat a private banker funding terrorists in a high-stakes game of poker at Casino Royale, Montenegro.",
        gradient: "from-neutral-900 via-neutral-950 to-red-950/30",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "🃏🥃🤵",
        tagline: "Discover how Bond became 007."
      },
      {
        id: "bond-skyfall",
        title: "Skyfall",
        year: 2012,
        duration: "143 min",
        rating: "7.8",
        director: "Sam Mendes",
        cast: ["Daniel Craig", "Javier Bardem", "Judi Dench", "Ralph Fiennes"],
        genre: ["Espionage", "Action"],
        description: "James Bond's loyalty to M is tested when her past comes back to haunt her. When MI6 comes under attack, 007 must track down and destroy the threat, no matter how personal the cost.",
        gradient: "from-slate-900 via-blue-950/20 to-neutral-950",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🏚️🚁🚇",
        tagline: "The past always resurfaces in the heart of a Scottish winter."
      },
      {
        id: "bond-no-time-to-die",
        title: "No Time to Die",
        year: 2021,
        duration: "163 min",
        rating: "7.3",
        director: "Cary Joji Fukunaga",
        cast: ["Daniel Craig", "Rami Malek", "Léa Seydoux", "Lashana Lynch"],
        genre: ["Espionage", "Action"],
        description: "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
        gradient: "from-neutral-900 via-zinc-900 to-indigo-950/30",
        accentColor: "text-slate-200 border-slate-300/30 bg-slate-300/10",
        accentHex: "#e2e8f0",
        symbol: "🚤🧬🥀",
        tagline: "The triumphant farewell of Commander Bond."
      }
    ]
  },
  {
    id: "rocky",
    title: "Rocky",
    description: "The fight of a lifetime. The inspiring rise of the Italian Stallion from a humble Philadelphia neighborhood to the top of the world.",
    movies: [
      {
        id: "rocky-1",
        title: "Rocky",
        year: 1976,
        duration: "120 min",
        rating: "8.1",
        director: "John G. Avildsen",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Carl Weathers"],
        genre: ["Sport", "Drama"],
        description: "Rocky Balboa, a boxer from a seedy Philadelphia club accumulating debts, is offered by a stroke of destiny to face the undefeated world champion Apollo Creed for a historic main event.",
        gradient: "from-neutral-900 via-amber-950/30 to-zinc-900",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🥊🏃🥩",
        tagline: "Everyone deserves a chance at glory."
      },
      {
        id: "rocky-2",
        title: "Rocky II",
        year: 1979,
        duration: "119 min",
        rating: "7.3",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Carl Weathers"],
        genre: ["Sport", "Drama"],
        description: "After heroically going the distance against world champion Apollo Creed, the public demands a spectacular rematch. Rocky Balboa first tries to settle down with his family before returning to the ring.",
        gradient: "from-neutral-900 via-stone-900 to-amber-950/20",
        accentColor: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
        accentHex: "#facc15",
        symbol: "💍🦁👊",
        tagline: "A rematch the whole world was waiting for."
      },
      {
        id: "rocky-3",
        title: "Rocky III",
        year: 1982,
        duration: "99 min",
        rating: "6.9",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Mr. T"],
        genre: ["Sport", "Drama"],
        description: "Rocky has rested on his laurels and suffers a crushing knockout defeat to the fierce and arrogant Clubber Lang. Apollo Creed, his former rival, steps up as an unexpected mentor to give him back the 'eye of the tiger'.",
        gradient: "from-neutral-900 via-amber-950/30 to-neutral-950",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#ca8a04",
        symbol: "🐯🏆⚡",
        tagline: "Rediscover the will to win."
      },
      {
        id: "rocky-4",
        title: "Rocky IV",
        year: 1985,
        duration: "91 min",
        rating: "6.9",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Talia Shire", "Carl Weathers", "Dolph Lundgren"],
        genre: ["Sport", "Drama"],
        description: "When his lifelong friend Apollo Creed dies tragically in the ring killed by the ruthless Soviet colossus Ivan Drago, Rocky Balboa decides to train hard in the heart of the wild Siberia to face him in Moscow.",
        gradient: "from-blue-950/40 via-red-950/30 to-neutral-900",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🧥❄️🇷🇺",
        tagline: "A fight that transcends geopolitical borders."
      },
      {
        id: "rocky-5",
        title: "Rocky V",
        year: 1990,
        duration: "104 min",
        rating: "5.3",
        director: "John G. Avildsen",
        cast: ["Sylvester Stallone", "Talia Shire", "Burt Young", "Tommy Morrison"],
        genre: ["Sport", "Drama"],
        description: "Financially ruined and forced to retire from boxing due to physical aftereffects, Rocky returns to the Philadelphia suburbs and trains a fiery young prodigy named Tommy Gunn.",
        gradient: "from-neutral-900 via-zinc-950 to-stone-900",
        accentColor: "text-neutral-400 border-neutral-400/30 bg-neutral-400/10",
        accentHex: "#94a3b8",
        symbol: "🏚️👦🏼🧥",
        tagline: "The real fight isn't in the ring."
      },
      {
        id: "rocky-6",
        title: "Rocky Balboa",
        year: 2006,
        duration: "102 min",
        rating: "7.1",
        director: "Sylvester Stallone",
        cast: ["Sylvester Stallone", "Burt Young", "Antonio Tarver", "Geraldine Hughes"],
        genre: ["Sport", "Drama"],
        description: "Owning a modest restaurant, Rocky still suffers from Adrian's death. When a TV simulation declares him the virtual winner of the current champion, Rocky agrees to don the gloves again for a final rematch of honor.",
        gradient: "from-stone-950 via-neutral-900 to-amber-950/15",
        accentColor: "text-amber-400 border-amber-400/30 bg-amber-400/10",
        accentHex: "#fbbf24",
        symbol: "🍽️🐕🏟️",
        tagline: "It's about how hard you can get hit and keep moving forward."
      }
    ]
  },
  {
    id: "terminator",
    title: "Terminator",
    description: "Human resistance against the uprising of Skynet and cyborgs. A time loop of pure cybernetic action.",
    movies: [
      {
        id: "terminator-1",
        title: "Terminator",
        year: 1984,
        duration: "107 min",
        rating: "8.1",
        director: "James Cameron",
        cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn"],
        genre: ["Science Fiction", "Action"],
        description: "In 1984, a cold cybernetic assassin created by Skynet - the T-800 - is sent from 2029 to kill Sarah Connor, whose unborn son John will lead humanity to victory in a future war against the machines.",
        gradient: "from-blue-950/50 via-neutral-900 to-slate-900",
        accentColor: "text-blue-400 border-blue-400/30 bg-blue-400/10",
        accentHex: "#60a5fa",
        symbol: "🕶️🏍️🚨",
        tagline: "I'll be back."
      },
      {
        id: "terminator-2",
        title: "Terminator 2: Judgment Day",
        year: 1991,
        duration: "137 min",
        rating: "8.6",
        director: "James Cameron",
        cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick"],
        genre: ["Science Fiction", "Action"],
        description: "A reprogrammed muscular T-800 is sent by the human resistance to protect a young John Connor from a highly advanced and nearly indestructible liquid metal cyborg: the T-1000.",
        gradient: "from-blue-950 via-zinc-900 to-amber-950/10",
        accentColor: "text-cyan-400 border-cyan-400/30 bg-cyan-400/10",
        accentHex: "#22d3ee",
        symbol: "🕶️🧪⛓️",
        tagline: "Hasta la vista, baby."
      },
      {
        id: "terminator-3",
        title: "Terminator 3: Rise of the Machines",
        year: 2003,
        duration: "109 min",
        rating: "6.3",
        director: "Jonathan Mostow",
        cast: ["Arnold Schwarzenegger", "Nick Stahl", "Claire Danes", "Kristanna Loken"],
        genre: ["Science Fiction", "Action"],
        description: "John Connor now lives off the grid to avoid detection. Unfortunately, Skynet manages to send the formidable T-X, a superpowered assassin, while an aging T-850 attempts to protect him.",
        gradient: "from-neutral-900 via-stone-900 to-red-950/30",
        accentColor: "text-red-400 border-red-400/30 bg-red-400/10",
        accentHex: "#f87171",
        symbol: "🔌💥👩‍🎤",
        tagline: "The awakening of the end of the world."
      },
      {
        id: "terminator-4",
        title: "Terminator Salvation",
        year: 2009,
        duration: "115 min",
        rating: "6.5",
        director: "McG",
        cast: ["Christian Bale", "Sam Worthington", "Moon Bloodgood", "Helena Bonham Carter"],
        genre: ["Science Fiction", "Action", "War"],
        description: "In 2018, after the cataclysm of Judgment Day, John Connor relentlessly leads the human resistance. He is confronted by Marcus Wright, a mysterious cybernetic death row inmate who believes he is still human.",
        gradient: "from-neutral-900 via-stone-950 to-neutral-800",
        accentColor: "text-emerald-400 border-emerald-400/30 bg-emerald-400/10",
        accentHex: "#34d399",
        symbol: "🛩️⚙️🤖",
        tagline: "The beginning of the end for Skynet."
      },
      {
        id: "terminator-5",
        title: "Terminator Genisys",
        year: 2015,
        duration: "126 min",
        rating: "6.3",
        director: "Alan Taylor",
        cast: ["Arnold Schwarzenegger", "Jason Clarke", "Emilia Clarke", "Jai Courtney"],
        genre: ["Science Fiction", "Action"],
        description: "By sending Kyle Reese back to 1984 to save Sarah, John triggers a temporal distortion. Reese arrives in a fractured past where Sarah Connor, raised by a protective T-800, is already a seasoned fighter.",
        gradient: "from-indigo-950/30 via-neutral-900 to-slate-950",
        accentColor: "text-purple-400 border-purple-400/30 bg-purple-400/10",
        accentHex: "#c084fc",
        symbol: "🧭🌀🛡️",
        tagline: "Reset the future."
      },
      {
        id: "terminator-6",
        title: "Terminator: Dark Fate",
        year: 2019,
        duration: "128 min",
        rating: "6.2",
        director: "Tim Miller",
        cast: ["Linda Hamilton", "Arnold Schwarzenegger", "Mackenzie Davis", "Natalia Reyes"],
        genre: ["Science Fiction", "Action"],
        description: "Nearly thirty years after Sarah Connor saved the world, an augmented human arrives to protect a young Mexican factory worker hunted by a highly advanced, separable Terminator prototype, the Rev-9.",
        gradient: "from-zinc-900 via-neutral-900 to-rose-950/20",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "🌪️💀🔫",
        tagline: "Welcome to the day after Judgment Day."
      }
    ]
  },
  
  {
    id: "mafia-movies",
    title: "Mafia",
    description: "The world of the underworld, goodfellas and cartels. Epic tales of power, loyalty and betrayal.",
    movies: [
      {
        id: "godfather-1",
        title: "The Godfather",
        year: 1972,
        duration: "175 min",
        rating: "9.2",
        director: "Francis Ford Coppola",
        cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
        genre: ["Crime", "Drama"],
        description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        gradient: "from-amber-950 via-stone-900 to-black",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🌹🥃🔫",
        tagline: "An offer you can't refuse."
      },
      {
        id: "bronx-tale",
        title: "A Bronx Tale",
        originalTitle: "A Bronx Tale",
        year: 1993,
        duration: "121 min",
        rating: "7.8",
        director: "Robert De Niro",
        cast: ["Robert De Niro", "Chazz Palminteri", "Lillo Brancato"],
        genre: ["Crime", "Drama"],
      },
      {
        id: "goodfellas",
        title: "Goodfellas",
        year: 1990,
        duration: "145 min",
        rating: "8.7",
        director: "Martin Scorsese",
        cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
        genre: ["Biography", "Crime", "Drama"],
        description: "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
        gradient: "from-red-950 via-neutral-900 to-stone-950",
        accentColor: "text-red-500 border-red-500/30 bg-red-500/10",
        accentHex: "#ef4444",
        symbol: "🍝🔫🚁",
        tagline: "As far back as I can remember, I always wanted to be a gangster."
      },
      {
        id: "scarface",
        title: "Scarface",
        year: 1983,
        duration: "170 min",
        rating: "8.3",
        director: "Brian De Palma",
        cast: ["Al Pacino", "Michelle Pfeiffer", "Steven Bauer", "Mary Elizabeth Mastrantonio"],
        genre: ["Crime", "Drama"],
        description: "In 1980, a Cuban immigrant arrives in Miami with nothing and eventually becomes a powerful drug kingpin.",
        gradient: "from-slate-900 via-rose-950/40 to-black",
        accentColor: "text-rose-500 border-rose-500/30 bg-rose-500/10",
        accentHex: "#f43f5e",
        symbol: "💰🌴🔫",
        tagline: "The world is yours."
      },
    {
        id: "godfather-2",
        title: "The Godfather Part II",
        year: 1974,
        duration: "202 min",
        rating: "9.0",
        director: "Francis Ford Coppola",
        cast: ["Al Pacino", "Robert De Niro", "Robert Duvall", "Diane Keaton"],
        genre: ["Crime", "Drama"],
        description: "The story of the Corleone family continues with Vito Corleone building his empire and Michael Corleone managing it in the 1950s.",
        gradient: "from-amber-950 via-stone-900 to-black",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🌹🥃🔫",
        tagline: "Keep your friends close, but your enemies closer."
      },
      {
        id: "godfather-3",
        title: "The Godfather Part III",
        year: 1990,
        duration: "162 min",
        rating: "7.6",
        director: "Francis Ford Coppola",
        cast: ["Al Pacino", "Diane Keaton", "Andy Garcia", "Talia Shire"],
        genre: ["Crime", "Drama"],
        description: "Michael Corleone attempts to legitimize his family's business but is pulled back in by the sins of his past.",
        gradient: "from-amber-950 via-stone-900 to-black",
        accentColor: "text-amber-500 border-amber-500/30 bg-amber-500/10",
        accentHex: "#f59e0b",
        symbol: "🌹🥃🔫",
        tagline: "Just when I thought I was out... they pull me back in."
      },
      {
        id: "irishman",
        title: "The Irishman",
        year: 2019,
        duration: "209 min",
        rating: "7.8",
        director: "Martin Scorsese",
        cast: ["Robert De Niro", "Al Pacino", "Joe Pesci", "Harvey Keitel"],
        genre: ["Biography", "Crime", "Drama"],
        description: "Frank Sheeran, a WWII veteran, hustler, and hitman, looks back on his past.",
        gradient: "from-zinc-900 via-neutral-900 to-stone-950",
        accentColor: "text-zinc-400 border-zinc-400/30 bg-zinc-400/10",
        accentHex: "#a1a1aa",
        symbol: "🇮🇪🔫👴",
        tagline: "I heard you paint houses."
      },
      {
        id: "american-gangster",
        title: "American Gangster",
        year: 2007,
        duration: "157 min",
        rating: "7.8",
        director: "Ridley Scott",
        cast: ["Denzel Washington", "Russell Crowe", "Chiwetel Ejiofor", "Josh Brolin"],
        genre: ["Biography", "Crime", "Drama"],
        description: "A New York cop is tasked with taking down the city's biggest drug lord.",
        gradient: "from-stone-900 via-neutral-900 to-black",
        accentColor: "text-stone-400 border-stone-400/30 bg-stone-400/10",
        accentHex: "#a8a29e",
        symbol: "🚔❄️💰",
        tagline: "There are dirty cops, and honest gangsters."
      },
      {
        id: "casino",
        title: "Casino",
        year: 1995,
        duration: "178 min",
        rating: "8.2",
        director: "Martin Scorsese",
        cast: ["Robert De Niro", "Sharon Stone", "Joe Pesci", "James Woods"],
        genre: ["Crime", "Drama"],
        description: "The story of the blind ambition and greed that led to the fall of a mafia gambling empire.",
        gradient: "from-yellow-950 via-stone-900 to-black",
        accentColor: "text-yellow-500 border-yellow-500/30 bg-yellow-500/10",
        accentHex: "#eab308",
        symbol: "🎰🎲💼",
        tagline: "No one stays at the top forever."
      }
    ]
  },
  {
    id: "mind-bending-mysteries",
    title: "Mysteries",
    description: "Chilling psychological thrillers, sordid murders and twists that will leave you speechless.",
    movies: [
      {
        id: "memories-of-murder",
        title: "Memories of Murder",
        posterUrl: "https://image.tmdb.org/t/p/w500/q3uYq9b2z3GZq2D5O9E5Q8O5O5O.jpg",
        originalTitle: "Salinui chueok",
        year: 2003,
        duration: "131 min",
        rating: "8.1",
        director: "Bong Joon Ho",
        cast: ["Song Kang-ho", "Kim Sang-kyung", "Kim Roe-ha"],
        genre: ["Crime", "Drama", "Mystery"],
      },
      {
        id: "se7en",
        title: "Se7en",
        year: 1995,
        duration: "127 min",
        rating: "8.6",
        director: "David Fincher",
        cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey"],
        genre: ["Crime", "Drama", "Mystery"],
        description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        gradient: "from-stone-900 via-yellow-950/20 to-black",
        accentColor: "text-stone-400 border-stone-400/30 bg-stone-400/10",
        accentHex: "#a8a29e",
        symbol: "📦🌧️🔍",
        tagline: "What's in the box?"
      },
      {
        id: "memento",
        title: "Memento",
        year: 2000,
        duration: "113 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano", "Mark Boone Junior"],
        genre: ["Mystery", "Thriller"],
        description: "A man suffering from anterograde amnesia uses notes and tattoos to hunt for the man he thinks killed his wife.",
        gradient: "from-slate-900 via-indigo-950/30 to-black",
        accentColor: "text-indigo-400 border-indigo-400/30 bg-indigo-400/10",
        accentHex: "#818cf8",
        symbol: "📸🖊️🧠",
        tagline: "Some memories are best forgotten."
      },
      {
        id: "zodiac",
        title: "Zodiac",
        year: 2007,
        duration: "157 min",
        rating: "7.7",
        director: "David Fincher",
        cast: ["Jake Gyllenhaal", "Robert Downey Jr.", "Mark Ruffalo", "Anthony Edwards"],
        genre: ["Crime", "Drama", "Mystery"],
        description: "The true story of the hunt for the Zodiac Killer, a serial killer who terrorized the San Francisco Bay Area in the late 1960s and 70s.",
        gradient: "from-stone-950 via-zinc-900 to-black",
        accentColor: "text-zinc-400 border-zinc-400/30 bg-zinc-400/10",
        accentHex: "#a1a1aa",
        symbol: "🗞️🕵️‍♂️✉️",
        tagline: "There is no end to obsession."
      },
      {
        id: "prisoners",
        title: "Prisoners",
        year: 2013,
        duration: "153 min",
        rating: "8.1",
        director: "Denis Villeneuve",
        cast: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Maria Bello"],
        genre: ["Crime", "Drama", "Mystery"],
        description: "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.",
        gradient: "from-neutral-950 via-stone-900 to-black",
        accentColor: "text-stone-300 border-stone-300/30 bg-stone-300/10",
        accentHex: "#d6d3d1",
        symbol: "❄️🚐🔎",
        tagline: "Every moment counts."
      }
    ]
  },
  {
    id: "the-batman",
    title: "The Batman",
    description: "The Dark Knight defends Gotham City against crime and corruption.",
    movies: [
      
      {
        id: "the-dark-knight",
        title: "The Dark Knight",
        year: 2008,
        duration: "152 min",
        rating: "9.0",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
        genre: ["Action", "Crime", "Drama"],
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        gradient: "from-zinc-900 via-neutral-900 to-black",
        accentColor: "text-purple-500 border-purple-500/30 bg-purple-500/10",
        accentHex: "#a855f7",
        symbol: "🦇🃏🔥",
        tagline: "Why so serious?"
      },
      {
        id: "the-dark-knight-rises",
        title: "The Dark Knight Rises",
        year: 2012,
        duration: "164 min",
        rating: "8.4",
        director: "Christopher Nolan",
        cast: ["Christian Bale", "Tom Hardy", "Anne Hathaway", "Gary Oldman"],
        genre: ["Action", "Crime", "Drama"],
        description: "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
        gradient: "from-stone-900 via-neutral-900 to-black",
        accentColor: "text-stone-400 border-stone-400/30 bg-stone-400/10",
        accentHex: "#a8a29e",
        symbol: "🦇💪🔥",
        tagline: "The end of a legend."
      },
      {
        id: "the-batman-2022",
        title: "The Batman",
        year: 2022,
        duration: "176 min",
        rating: "7.8",
        director: "Matt Reeves",
        cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano", "Colin Farrell"],
        genre: ["Action", "Crime", "Drama"],
        description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
        gradient: "from-red-950/40 via-neutral-900 to-black",
        accentColor: "text-red-600 border-red-600/30 bg-red-600/10",
        accentHex: "#dc2626",
        symbol: "🦇❓🌧️",
        tagline: "Unmask the truth."
      }
    ]
  }
];
